import type { PortalState } from './types';

const nowIso = (): string => new Date().toISOString();

export const createDefaultPortalState = (): PortalState => ({
  audit_log: [
    {
      action: 'Портал запущен, загружены начальные данные контента',
      actor_label: 'Система',
      created_at: nowIso(),
      id: 'audit-seed',
    },
  ],
  banners: {
    delay_sec: 6,
    items: [],
  },
  content: {
    about: {
      cta_badge: '',
      cta_button: '',
      cta_hint: '',
      cta_text: '',
      cta_title: '',
      directions_badge: '',
      directions_subtitle: '',
      directions_title: '',
      hero_badge: '',
      hero_subtitle: '',
      offices: [],
      offices_badge: '',
      offices_subtitle: '',
      offices_title: '',
      profile_badge: '',
      profile_title: '',
      text: '',
      title: '',
    },
    certificates: {
      items: [],
      text: '',
      title: '',
    },
    contacts: {
      address: '',
      email: '',
      managers: [],
      offices: [],
      phone: '',
      requisite_items: [],
      requisites: '',
      subtitle: '',
      title: '',
      warehouse_map_caption: '',
      warehouse_map_url: '',
      work_hours: '',
    },
    home: {
      features: [],
      hero_button: '',
      hero_subtitle: '',
      hero_title: '',
      stats: [],
      why_items: [],
      why_title: '',
    },
    promo: {
      items: [],
      text: '',
      title: '',
    },
    terms: {
      description: '',
      eyebrow: '',
      terms: [],
      title: '',
    },
  },
  email_log: [],
  feedback: [],
  legal_docs: [],
  portal_users: [],
  signup_requests: [],
  support_requests: [],
});
