// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/access/pkg/interfaces/internalAPI"
)

type httpAccessAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverAccessAPI
	base             internalAPI.AccessAPI
}

func NewAccessAPI(svcAccessAPI internalAPI.AccessAPI) (srv *httpAccessAPI) {

	srv = &httpAccessAPI{
		base: svcAccessAPI,
		svc:  newServerAccessAPI(svcAccessAPI),
	}
	return
}

func (http *httpAccessAPI) Service() *serverAccessAPI {
	return http.svc
}

func (http *httpAccessAPI) WithLog() *httpAccessAPI {
	http.svc.WithLog()
	return http
}

func (http *httpAccessAPI) WithMetrics() *httpAccessAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpAccessAPI) WithErrorHandler(handler ErrorHandler) *httpAccessAPI {
	http.errorHandler = handler
	return http
}

func (http *httpAccessAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/access/check", http.serveCheckAccess)
	route.Post("/api/v1/access/role/add", http.serveAddRole)
	route.Post("/api/v1/access/role/update", http.serveUpdateRole)
	route.Post("/api/v1/access/role/delete", http.serveDeleteRole)
}
