// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/access/internal/transport/jsonRPC/internalapi/viewer"
	"github.com/mbatimel/AMC/access/pkg/interfaces/internalAPI"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerAccessAPI struct {
	next internalAPI.AccessAPI
}

func loggerMiddlewareAccessAPI() MiddlewareAccessAPI {
	return func(next internalAPI.AccessAPI) internalAPI.AccessAPI {
		return &loggerAccessAPI{next: next}
	}
}

func (m loggerAccessAPI) CheckAccess(ctx context.Context, userID uuid.UUID, role int) (allowed bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AccessAPI").Str("method", "checkAccess").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "accessAPI.checkAccess",
				"request": viewer.Sprintf("%+v", requestAccessAPICheckAccess{
					Role:   role,
					UserID: userID,
				}),
				"response": viewer.Sprintf("%+v", responseAccessAPICheckAccess{Allowed: allowed}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call checkAccess")
			return
		}
		logger.Info().Func(logHandle).Msg("call checkAccess")
	}(time.Now())
	return m.next.CheckAccess(ctx, userID, role)
}

func (m loggerAccessAPI) AddRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AccessAPI").Str("method", "addRole").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "accessAPI.addRole",
				"request": viewer.Sprintf("%+v", requestAccessAPIAddRole{
					AdminUserID: adminUserID,
					Role:        role,
					UserID:      userID,
				}),
				"response": viewer.Sprintf("%+v", responseAccessAPIAddRole{Success: success}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call addRole")
			return
		}
		logger.Info().Func(logHandle).Msg("call addRole")
	}(time.Now())
	return m.next.AddRole(ctx, adminUserID, userID, role)
}

func (m loggerAccessAPI) UpdateRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AccessAPI").Str("method", "updateRole").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "accessAPI.updateRole",
				"request": viewer.Sprintf("%+v", requestAccessAPIUpdateRole{
					AdminUserID: adminUserID,
					Role:        role,
					UserID:      userID,
				}),
				"response": viewer.Sprintf("%+v", responseAccessAPIUpdateRole{Success: success}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateRole")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateRole")
	}(time.Now())
	return m.next.UpdateRole(ctx, adminUserID, userID, role)
}

func (m loggerAccessAPI) DeleteRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AccessAPI").Str("method", "deleteRole").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "accessAPI.deleteRole",
				"request": viewer.Sprintf("%+v", requestAccessAPIDeleteRole{
					AdminUserID: adminUserID,
					Role:        role,
					UserID:      userID,
				}),
				"response": viewer.Sprintf("%+v", responseAccessAPIDeleteRole{Success: success}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteRole")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteRole")
	}(time.Now())
	return m.next.DeleteRole(ctx, adminUserID, userID, role)
}
