// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/access/pkg/interfaces/internalAPI"
)

type serverAccessAPI struct {
	svc         internalAPI.AccessAPI
	checkAccess AccessAPICheckAccess
	addRole     AccessAPIAddRole
	updateRole  AccessAPIUpdateRole
	deleteRole  AccessAPIDeleteRole
}

type MiddlewareSetAccessAPI interface {
	Wrap(m MiddlewareAccessAPI)
	WrapCheckAccess(m MiddlewareAccessAPICheckAccess)
	WrapAddRole(m MiddlewareAccessAPIAddRole)
	WrapUpdateRole(m MiddlewareAccessAPIUpdateRole)
	WrapDeleteRole(m MiddlewareAccessAPIDeleteRole)

	WithMetrics()
	WithLog()
}

func newServerAccessAPI(svc internalAPI.AccessAPI) *serverAccessAPI {
	return &serverAccessAPI{
		addRole:     svc.AddRole,
		checkAccess: svc.CheckAccess,
		deleteRole:  svc.DeleteRole,
		svc:         svc,
		updateRole:  svc.UpdateRole,
	}
}

func (srv *serverAccessAPI) Wrap(m MiddlewareAccessAPI) {
	srv.svc = m(srv.svc)
	srv.checkAccess = srv.svc.CheckAccess
	srv.addRole = srv.svc.AddRole
	srv.updateRole = srv.svc.UpdateRole
	srv.deleteRole = srv.svc.DeleteRole
}

func (srv *serverAccessAPI) CheckAccess(ctx context.Context, userID uuid.UUID, role int) (allowed bool, err error) {
	return srv.checkAccess(ctx, userID, role)
}

func (srv *serverAccessAPI) AddRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	return srv.addRole(ctx, adminUserID, userID, role)
}

func (srv *serverAccessAPI) UpdateRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	return srv.updateRole(ctx, adminUserID, userID, role)
}

func (srv *serverAccessAPI) DeleteRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {
	return srv.deleteRole(ctx, adminUserID, userID, role)
}

func (srv *serverAccessAPI) WrapCheckAccess(m MiddlewareAccessAPICheckAccess) {
	srv.checkAccess = m(srv.checkAccess)
}

func (srv *serverAccessAPI) WrapAddRole(m MiddlewareAccessAPIAddRole) {
	srv.addRole = m(srv.addRole)
}

func (srv *serverAccessAPI) WrapUpdateRole(m MiddlewareAccessAPIUpdateRole) {
	srv.updateRole = m(srv.updateRole)
}

func (srv *serverAccessAPI) WrapDeleteRole(m MiddlewareAccessAPIDeleteRole) {
	srv.deleteRole = m(srv.deleteRole)
}

func (srv *serverAccessAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAccessAPI)
}

func (srv *serverAccessAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAccessAPI())
}
