// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import "github.com/google/uuid"

type requestAccessAPICheckAccess struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Role   int       `json:"role,omitempty"`
}

type responseAccessAPICheckAccess struct {
	Allowed bool `json:"allowed,omitempty"`
}

type requestAccessAPIAddRole struct {
	AdminUserID uuid.UUID `json:"adminUserID,omitempty"`
	UserID      uuid.UUID `json:"userID,omitempty"`
	Role        int       `json:"role,omitempty"`
}

type responseAccessAPIAddRole struct {
	Success bool `json:"success,omitempty"`
}

type requestAccessAPIUpdateRole struct {
	AdminUserID uuid.UUID `json:"adminUserID,omitempty"`
	UserID      uuid.UUID `json:"userID,omitempty"`
	Role        int       `json:"role,omitempty"`
}

type responseAccessAPIUpdateRole struct {
	Success bool `json:"success,omitempty"`
}

type requestAccessAPIDeleteRole struct {
	AdminUserID uuid.UUID `json:"adminUserID,omitempty"`
	UserID      uuid.UUID `json:"userID,omitempty"`
	Role        int       `json:"role,omitempty"`
}

type responseAccessAPIDeleteRole struct {
	Success bool `json:"success,omitempty"`
}
