// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
)

func (http *httpAccessAPI) checkAccess(ctx context.Context, request requestAccessAPICheckAccess) (response responseAccessAPICheckAccess, err error) {

	response.Allowed, err = http.svc.CheckAccess(ctx, request.UserID, request.Role)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAccessAPI) serveCheckAccess(ctx *fiber.Ctx) (err error) {

	var request requestAccessAPICheckAccess

	if _userID := ctx.Query("userID"); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}
	if _role := ctx.Query("role"); _role != "" {
		var role int
		role, err = strconv.Atoi(_role)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Role = role
	}

	var response responseAccessAPICheckAccess
	if response, err = http.checkAccess(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAccessAPI) addRole(ctx context.Context, request requestAccessAPIAddRole) (response responseAccessAPIAddRole, err error) {

	response.Success, err = http.svc.AddRole(ctx, request.AdminUserID, request.UserID, request.Role)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAccessAPI) serveAddRole(ctx *fiber.Ctx) (err error) {

	var request requestAccessAPIAddRole

	if _userID := ctx.Query("userID"); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}
	if _role := ctx.Query("role"); _role != "" {
		var role int
		role, err = strconv.Atoi(_role)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Role = role
	}

	if _adminUserID := string(ctx.Request().Header.Peek("X-Admin-User-Id")); _adminUserID != "" {
		var adminUserID uuid.UUID
		adminUserID, _ = uuid.Parse(_adminUserID)
		request.AdminUserID = adminUserID
	}

	var response responseAccessAPIAddRole
	if response, err = http.addRole(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAccessAPI) updateRole(ctx context.Context, request requestAccessAPIUpdateRole) (response responseAccessAPIUpdateRole, err error) {

	response.Success, err = http.svc.UpdateRole(ctx, request.AdminUserID, request.UserID, request.Role)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAccessAPI) serveUpdateRole(ctx *fiber.Ctx) (err error) {

	var request requestAccessAPIUpdateRole

	if _role := ctx.Query("role"); _role != "" {
		var role int
		role, err = strconv.Atoi(_role)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Role = role
	}
	if _userID := ctx.Query("userID"); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	if _adminUserID := string(ctx.Request().Header.Peek("X-Admin-User-Id")); _adminUserID != "" {
		var adminUserID uuid.UUID
		adminUserID, _ = uuid.Parse(_adminUserID)
		request.AdminUserID = adminUserID
	}

	var response responseAccessAPIUpdateRole
	if response, err = http.updateRole(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAccessAPI) deleteRole(ctx context.Context, request requestAccessAPIDeleteRole) (response responseAccessAPIDeleteRole, err error) {

	response.Success, err = http.svc.DeleteRole(ctx, request.AdminUserID, request.UserID, request.Role)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAccessAPI) serveDeleteRole(ctx *fiber.Ctx) (err error) {

	var request requestAccessAPIDeleteRole

	if _userID := ctx.Query("userID"); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}
	if _role := ctx.Query("role"); _role != "" {
		var role int
		role, err = strconv.Atoi(_role)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Role = role
	}

	if _adminUserID := string(ctx.Request().Header.Peek("X-Admin-User-Id")); _adminUserID != "" {
		var adminUserID uuid.UUID
		adminUserID, _ = uuid.Parse(_adminUserID)
		request.AdminUserID = adminUserID
	}

	var response responseAccessAPIDeleteRole
	if response, err = http.deleteRole(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
