// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/access/pkg/interfaces/internalAPI"
)

type AccessAPICheckAccess func(ctx context.Context, userID uuid.UUID, role int) (allowed bool, err error)
type AccessAPIAddRole func(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error)
type AccessAPIUpdateRole func(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error)
type AccessAPIDeleteRole func(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error)

type MiddlewareAccessAPI func(next internalAPI.AccessAPI) internalAPI.AccessAPI

type MiddlewareAccessAPICheckAccess func(next AccessAPICheckAccess) AccessAPICheckAccess
type MiddlewareAccessAPIAddRole func(next AccessAPIAddRole) AccessAPIAddRole
type MiddlewareAccessAPIUpdateRole func(next AccessAPIUpdateRole) AccessAPIUpdateRole
type MiddlewareAccessAPIDeleteRole func(next AccessAPIDeleteRole) AccessAPIDeleteRole
