// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/platforms/pkg/interfaces/externalapi"
)

type httpPlatformsAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverPlatformsAPI
	base             externalapi.PlatformsAPI
}

func NewPlatformsAPI(svcPlatformsAPI externalapi.PlatformsAPI) (srv *httpPlatformsAPI) {

	srv = &httpPlatformsAPI{
		base: svcPlatformsAPI,
		svc:  newServerPlatformsAPI(svcPlatformsAPI),
	}
	return
}

func (http *httpPlatformsAPI) Service() *serverPlatformsAPI {
	return http.svc
}

func (http *httpPlatformsAPI) WithLog() *httpPlatformsAPI {
	http.svc.WithLog()
	return http
}

func (http *httpPlatformsAPI) WithMetrics() *httpPlatformsAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpPlatformsAPI) WithErrorHandler(handler ErrorHandler) *httpPlatformsAPI {
	http.errorHandler = handler
	return http
}

func (http *httpPlatformsAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/wildberries/cards", http.serveCreateWildberriesCard)
	route.Post("/api/v1/ozon/cards", http.serveCreateOzonCard)
	route.Post("/api/v1/yandex-market/cards", http.serveCreateYandexMarketCard)
}
