// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/platforms/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/platforms/pkg/models"
)

type serverPlatformsAPI struct {
	svc                    externalapi.PlatformsAPI
	createWildberriesCard  PlatformsAPICreateWildberriesCard
	createOzonCard         PlatformsAPICreateOzonCard
	createYandexMarketCard PlatformsAPICreateYandexMarketCard
}

type MiddlewareSetPlatformsAPI interface {
	Wrap(m MiddlewarePlatformsAPI)
	WrapCreateWildberriesCard(m MiddlewarePlatformsAPICreateWildberriesCard)
	WrapCreateOzonCard(m MiddlewarePlatformsAPICreateOzonCard)
	WrapCreateYandexMarketCard(m MiddlewarePlatformsAPICreateYandexMarketCard)

	WithMetrics()
	WithLog()
}

func newServerPlatformsAPI(svc externalapi.PlatformsAPI) *serverPlatformsAPI {
	return &serverPlatformsAPI{
		createOzonCard:         svc.CreateOzonCard,
		createWildberriesCard:  svc.CreateWildberriesCard,
		createYandexMarketCard: svc.CreateYandexMarketCard,
		svc:                    svc,
	}
}

func (srv *serverPlatformsAPI) Wrap(m MiddlewarePlatformsAPI) {
	srv.svc = m(srv.svc)
	srv.createWildberriesCard = srv.svc.CreateWildberriesCard
	srv.createOzonCard = srv.svc.CreateOzonCard
	srv.createYandexMarketCard = srv.svc.CreateYandexMarketCard
}

func (srv *serverPlatformsAPI) CreateWildberriesCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, subjectID int, vendorCode string, title string, description string, brand string, kizMarked bool, wholesaleEnabled bool, wholesaleQuantum int, dimensions models.WildberriesDimensions, sizes []models.WildberriesSize, characteristics []models.WildberriesCharacteristic, documents models.WildberriesDocuments) (response models.CreateWildberriesCardResponse, err error) {
	return srv.createWildberriesCard(ctx, userID, productID, subjectID, vendorCode, title, description, brand, kizMarked, wholesaleEnabled, wholesaleQuantum, dimensions, sizes, characteristics, documents)
}

func (srv *serverPlatformsAPI) CreateOzonCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, descriptionCategoryID int64, typeID int64, currencyCode string, price string, oldPrice string, vat string, barcode string, dimensions models.OzonDimensions, images []string, primaryImage string, colorImage string, attributes []models.OzonAttribute) (response models.CreateOzonCardResponse, err error) {
	return srv.createOzonCard(ctx, userID, productID, offerID, name, descriptionCategoryID, typeID, currencyCode, price, oldPrice, vat, barcode, dimensions, images, primaryImage, colorImage, attributes)
}

func (srv *serverPlatformsAPI) CreateYandexMarketCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, marketCategoryID int64, description string, vendor string, vendorCode string, pictures []string, barcodes []string, dimensions models.YandexMarketDimensions, parameterValues []models.YandexMarketParameterValue) (response models.CreateYandexMarketCardResponse, err error) {
	return srv.createYandexMarketCard(ctx, userID, productID, offerID, name, marketCategoryID, description, vendor, vendorCode, pictures, barcodes, dimensions, parameterValues)
}

func (srv *serverPlatformsAPI) WrapCreateWildberriesCard(m MiddlewarePlatformsAPICreateWildberriesCard) {
	srv.createWildberriesCard = m(srv.createWildberriesCard)
}

func (srv *serverPlatformsAPI) WrapCreateOzonCard(m MiddlewarePlatformsAPICreateOzonCard) {
	srv.createOzonCard = m(srv.createOzonCard)
}

func (srv *serverPlatformsAPI) WrapCreateYandexMarketCard(m MiddlewarePlatformsAPICreateYandexMarketCard) {
	srv.createYandexMarketCard = m(srv.createYandexMarketCard)
}

func (srv *serverPlatformsAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewarePlatformsAPI)
}

func (srv *serverPlatformsAPI) WithLog() {
	srv.Wrap(loggerMiddlewarePlatformsAPI())
}
