// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/platforms/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/platforms/pkg/models"
)

type PlatformsAPICreateWildberriesCard func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, subjectID int, vendorCode string, title string, description string, brand string, kizMarked bool, wholesaleEnabled bool, wholesaleQuantum int, dimensions models.WildberriesDimensions, sizes []models.WildberriesSize, characteristics []models.WildberriesCharacteristic, documents models.WildberriesDocuments) (response models.CreateWildberriesCardResponse, err error)
type PlatformsAPICreateOzonCard func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, descriptionCategoryID int64, typeID int64, currencyCode string, price string, oldPrice string, vat string, barcode string, dimensions models.OzonDimensions, images []string, primaryImage string, colorImage string, attributes []models.OzonAttribute) (response models.CreateOzonCardResponse, err error)
type PlatformsAPICreateYandexMarketCard func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, marketCategoryID int64, description string, vendor string, vendorCode string, pictures []string, barcodes []string, dimensions models.YandexMarketDimensions, parameterValues []models.YandexMarketParameterValue) (response models.CreateYandexMarketCardResponse, err error)

type MiddlewarePlatformsAPI func(next externalapi.PlatformsAPI) externalapi.PlatformsAPI

type MiddlewarePlatformsAPICreateWildberriesCard func(next PlatformsAPICreateWildberriesCard) PlatformsAPICreateWildberriesCard
type MiddlewarePlatformsAPICreateOzonCard func(next PlatformsAPICreateOzonCard) PlatformsAPICreateOzonCard
type MiddlewarePlatformsAPICreateYandexMarketCard func(next PlatformsAPICreateYandexMarketCard) PlatformsAPICreateYandexMarketCard
