// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
	customhandlers "github.com/mbatimel/AMC/platforms/internal/transport/custom-handlers"
)

func (http *httpPlatformsAPI) createWildberriesCard(ctx context.Context, request requestPlatformsAPICreateWildberriesCard) (response responsePlatformsAPICreateWildberriesCard, err error) {

	response.Response, err = http.svc.CreateWildberriesCard(ctx, request.UserID, request.ProductID, request.SubjectID, request.VendorCode, request.Title, request.Description, request.Brand, request.KizMarked, request.WholesaleEnabled, request.WholesaleQuantum, request.Dimensions, request.Sizes, request.Characteristics, request.Documents)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPlatformsAPI) serveCreateWildberriesCard(ctx *fiber.Ctx) (err error) {

	var request requestPlatformsAPICreateWildberriesCard
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.CreateWildberriesCard(ctx, http.svc, request.UserID, request.ProductID, request.SubjectID, request.VendorCode, request.Title, request.Description, request.Brand, request.KizMarked, request.WholesaleEnabled, request.WholesaleQuantum, request.Dimensions, request.Sizes, request.Characteristics, request.Documents)
}
func (http *httpPlatformsAPI) createOzonCard(ctx context.Context, request requestPlatformsAPICreateOzonCard) (response responsePlatformsAPICreateOzonCard, err error) {

	response.Response, err = http.svc.CreateOzonCard(ctx, request.UserID, request.ProductID, request.OfferID, request.Name, request.DescriptionCategoryID, request.TypeID, request.CurrencyCode, request.Price, request.OldPrice, request.Vat, request.Barcode, request.Dimensions, request.Images, request.PrimaryImage, request.ColorImage, request.Attributes)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPlatformsAPI) serveCreateOzonCard(ctx *fiber.Ctx) (err error) {

	var request requestPlatformsAPICreateOzonCard
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.CreateOzonCard(ctx, http.svc, request.UserID, request.ProductID, request.OfferID, request.Name, request.DescriptionCategoryID, request.TypeID, request.CurrencyCode, request.Price, request.OldPrice, request.Vat, request.Barcode, request.Dimensions, request.Images, request.PrimaryImage, request.ColorImage, request.Attributes)
}
func (http *httpPlatformsAPI) createYandexMarketCard(ctx context.Context, request requestPlatformsAPICreateYandexMarketCard) (response responsePlatformsAPICreateYandexMarketCard, err error) {

	response.Response, err = http.svc.CreateYandexMarketCard(ctx, request.UserID, request.ProductID, request.OfferID, request.Name, request.MarketCategoryID, request.Description, request.Vendor, request.VendorCode, request.Pictures, request.Barcodes, request.Dimensions, request.ParameterValues)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpPlatformsAPI) serveCreateYandexMarketCard(ctx *fiber.Ctx) (err error) {

	var request requestPlatformsAPICreateYandexMarketCard
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.CreateYandexMarketCard(ctx, http.svc, request.UserID, request.ProductID, request.OfferID, request.Name, request.MarketCategoryID, request.Description, request.Vendor, request.VendorCode, request.Pictures, request.Barcodes, request.Dimensions, request.ParameterValues)
}
