// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"
	"time"

	v2 "github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/platforms/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/platforms/pkg/models"
)

type metricsPlatformsAPI struct {
	next externalapi.PlatformsAPI
}

func metricsMiddlewarePlatformsAPI(next externalapi.PlatformsAPI) externalapi.PlatformsAPI {
	return &metricsPlatformsAPI{next: next}
}

func (m metricsPlatformsAPI) CreateWildberriesCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, subjectID int, vendorCode string, title string, description string, brand string, kizMarked bool, wholesaleEnabled bool, wholesaleQuantum int, dimensions models.WildberriesDimensions, sizes []models.WildberriesSize, characteristics []models.WildberriesCharacteristic, documents models.WildberriesDocuments) (response models.CreateWildberriesCardResponse, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("platformsAPI", "createWildberriesCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("platformsAPI", "createWildberriesCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("platformsAPI", "createWildberriesCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.CreateWildberriesCard(ctx, userID, productID, subjectID, vendorCode, title, description, brand, kizMarked, wholesaleEnabled, wholesaleQuantum, dimensions, sizes, characteristics, documents)
}

func (m metricsPlatformsAPI) CreateOzonCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, descriptionCategoryID int64, typeID int64, currencyCode string, price string, oldPrice string, vat string, barcode string, dimensions models.OzonDimensions, images []string, primaryImage string, colorImage string, attributes []models.OzonAttribute) (response models.CreateOzonCardResponse, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("platformsAPI", "createOzonCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("platformsAPI", "createOzonCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("platformsAPI", "createOzonCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.CreateOzonCard(ctx, userID, productID, offerID, name, descriptionCategoryID, typeID, currencyCode, price, oldPrice, vat, barcode, dimensions, images, primaryImage, colorImage, attributes)
}

func (m metricsPlatformsAPI) CreateYandexMarketCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, marketCategoryID int64, description string, vendor string, vendorCode string, pictures []string, barcodes []string, dimensions models.YandexMarketDimensions, parameterValues []models.YandexMarketParameterValue) (response models.CreateYandexMarketCardResponse, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("platformsAPI", "createYandexMarketCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("platformsAPI", "createYandexMarketCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("platformsAPI", "createYandexMarketCard", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.CreateYandexMarketCard(ctx, userID, productID, offerID, name, marketCategoryID, description, vendor, vendorCode, pictures, barcodes, dimensions, parameterValues)
}
