// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/platforms/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/AMC/platforms/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/platforms/pkg/models"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerPlatformsAPI struct {
	next externalapi.PlatformsAPI
}

func loggerMiddlewarePlatformsAPI() MiddlewarePlatformsAPI {
	return func(next externalapi.PlatformsAPI) externalapi.PlatformsAPI {
		return &loggerPlatformsAPI{next: next}
	}
}

func (m loggerPlatformsAPI) CreateWildberriesCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, subjectID int, vendorCode string, title string, description string, brand string, kizMarked bool, wholesaleEnabled bool, wholesaleQuantum int, dimensions models.WildberriesDimensions, sizes []models.WildberriesSize, characteristics []models.WildberriesCharacteristic, documents models.WildberriesDocuments) (response models.CreateWildberriesCardResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PlatformsAPI").Str("method", "createWildberriesCard").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "platformsAPI.createWildberriesCard",
				"request": viewer.Sprintf("%+v", requestPlatformsAPICreateWildberriesCard{
					Brand:            brand,
					Characteristics:  characteristics,
					Description:      description,
					Dimensions:       dimensions,
					Documents:        documents,
					KizMarked:        kizMarked,
					ProductID:        productID,
					Sizes:            sizes,
					SubjectID:        subjectID,
					Title:            title,
					UserID:           userID,
					VendorCode:       vendorCode,
					WholesaleEnabled: wholesaleEnabled,
					WholesaleQuantum: wholesaleQuantum,
				}),
				"response": viewer.Sprintf("%+v", responsePlatformsAPICreateWildberriesCard{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createWildberriesCard")
			return
		}
		logger.Info().Func(logHandle).Msg("call createWildberriesCard")
	}(time.Now())
	return m.next.CreateWildberriesCard(ctx, userID, productID, subjectID, vendorCode, title, description, brand, kizMarked, wholesaleEnabled, wholesaleQuantum, dimensions, sizes, characteristics, documents)
}

func (m loggerPlatformsAPI) CreateOzonCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, descriptionCategoryID int64, typeID int64, currencyCode string, price string, oldPrice string, vat string, barcode string, dimensions models.OzonDimensions, images []string, primaryImage string, colorImage string, attributes []models.OzonAttribute) (response models.CreateOzonCardResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PlatformsAPI").Str("method", "createOzonCard").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "platformsAPI.createOzonCard",
				"request": viewer.Sprintf("%+v", requestPlatformsAPICreateOzonCard{
					Attributes:            attributes,
					Barcode:               barcode,
					ColorImage:            colorImage,
					CurrencyCode:          currencyCode,
					DescriptionCategoryID: descriptionCategoryID,
					Dimensions:            dimensions,
					Images:                images,
					Name:                  name,
					OfferID:               offerID,
					OldPrice:              oldPrice,
					Price:                 price,
					PrimaryImage:          primaryImage,
					ProductID:             productID,
					TypeID:                typeID,
					UserID:                userID,
					Vat:                   vat,
				}),
				"response": viewer.Sprintf("%+v", responsePlatformsAPICreateOzonCard{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createOzonCard")
			return
		}
		logger.Info().Func(logHandle).Msg("call createOzonCard")
	}(time.Now())
	return m.next.CreateOzonCard(ctx, userID, productID, offerID, name, descriptionCategoryID, typeID, currencyCode, price, oldPrice, vat, barcode, dimensions, images, primaryImage, colorImage, attributes)
}

func (m loggerPlatformsAPI) CreateYandexMarketCard(ctx context.Context, userID uuid.UUID, productID uuid.UUID, offerID string, name string, marketCategoryID int64, description string, vendor string, vendorCode string, pictures []string, barcodes []string, dimensions models.YandexMarketDimensions, parameterValues []models.YandexMarketParameterValue) (response models.CreateYandexMarketCardResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "PlatformsAPI").Str("method", "createYandexMarketCard").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "platformsAPI.createYandexMarketCard",
				"request": viewer.Sprintf("%+v", requestPlatformsAPICreateYandexMarketCard{
					Barcodes:         barcodes,
					Description:      description,
					Dimensions:       dimensions,
					MarketCategoryID: marketCategoryID,
					Name:             name,
					OfferID:          offerID,
					ParameterValues:  parameterValues,
					Pictures:         pictures,
					ProductID:        productID,
					UserID:           userID,
					Vendor:           vendor,
					VendorCode:       vendorCode,
				}),
				"response": viewer.Sprintf("%+v", responsePlatformsAPICreateYandexMarketCard{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createYandexMarketCard")
			return
		}
		logger.Info().Func(logHandle).Msg("call createYandexMarketCard")
	}(time.Now())
	return m.next.CreateYandexMarketCard(ctx, userID, productID, offerID, name, marketCategoryID, description, vendor, vendorCode, pictures, barcodes, dimensions, parameterValues)
}
