// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/platforms/pkg/models"
)

type requestPlatformsAPICreateWildberriesCard struct {
	UserID           uuid.UUID                          `json:"userID,omitempty"`
	ProductID        uuid.UUID                          `json:"productID,omitempty"`
	SubjectID        int                                `json:"subjectID,omitempty"`
	VendorCode       string                             `json:"vendorCode,omitempty"`
	Title            string                             `json:"title,omitempty"`
	Description      string                             `json:"description,omitempty"`
	Brand            string                             `json:"brand,omitempty"`
	KizMarked        bool                               `json:"kizMarked,omitempty"`
	WholesaleEnabled bool                               `json:"wholesaleEnabled,omitempty"`
	WholesaleQuantum int                                `json:"wholesaleQuantum,omitempty"`
	Dimensions       models.WildberriesDimensions       `json:"dimensions,omitempty"`
	Sizes            []models.WildberriesSize           `json:"sizes,omitempty"`
	Characteristics  []models.WildberriesCharacteristic `json:"characteristics,omitempty"`
	Documents        models.WildberriesDocuments        `json:"documents,omitempty"`
}

type responsePlatformsAPICreateWildberriesCard struct {
	Response models.CreateWildberriesCardResponse `json:"response,omitempty"`
}

type requestPlatformsAPICreateOzonCard struct {
	UserID                uuid.UUID              `json:"userID,omitempty"`
	ProductID             uuid.UUID              `json:"productID,omitempty"`
	OfferID               string                 `json:"offerID,omitempty"`
	Name                  string                 `json:"name,omitempty"`
	DescriptionCategoryID int64                  `json:"descriptionCategoryID,omitempty"`
	TypeID                int64                  `json:"typeID,omitempty"`
	CurrencyCode          string                 `json:"currencyCode,omitempty"`
	Price                 string                 `json:"price,omitempty"`
	OldPrice              string                 `json:"oldPrice,omitempty"`
	Vat                   string                 `json:"vat,omitempty"`
	Barcode               string                 `json:"barcode,omitempty"`
	Dimensions            models.OzonDimensions  `json:"dimensions,omitempty"`
	Images                []string               `json:"images,omitempty"`
	PrimaryImage          string                 `json:"primaryImage,omitempty"`
	ColorImage            string                 `json:"colorImage,omitempty"`
	Attributes            []models.OzonAttribute `json:"attributes,omitempty"`
}

type responsePlatformsAPICreateOzonCard struct {
	Response models.CreateOzonCardResponse `json:"response,omitempty"`
}

type requestPlatformsAPICreateYandexMarketCard struct {
	UserID           uuid.UUID                           `json:"userID,omitempty"`
	ProductID        uuid.UUID                           `json:"productID,omitempty"`
	OfferID          string                              `json:"offerID,omitempty"`
	Name             string                              `json:"name,omitempty"`
	MarketCategoryID int64                               `json:"marketCategoryID,omitempty"`
	Description      string                              `json:"description,omitempty"`
	Vendor           string                              `json:"vendor,omitempty"`
	VendorCode       string                              `json:"vendorCode,omitempty"`
	Pictures         []string                            `json:"pictures,omitempty"`
	Barcodes         []string                            `json:"barcodes,omitempty"`
	Dimensions       models.YandexMarketDimensions       `json:"dimensions,omitempty"`
	ParameterValues  []models.YandexMarketParameterValue `json:"parameterValues,omitempty"`
}

type responsePlatformsAPICreateYandexMarketCard struct {
	Response models.CreateYandexMarketCardResponse `json:"response,omitempty"`
}
