// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
)

func (http *httpProductsInternalAPI) setMarketplaceStatus(ctx context.Context, request requestProductsInternalAPISetMarketplaceStatus) (response responseProductsInternalAPISetMarketplaceStatus, err error) {

	response.Ok, err = http.svc.SetMarketplaceStatus(ctx, request.ProductID, request.Marketplace, request.Status)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsInternalAPI) serveSetMarketplaceStatus(ctx *fiber.Ctx) (err error) {

	var request requestProductsInternalAPISetMarketplaceStatus

	if _productID := ctx.Query("productID"); _productID != "" {
		var productID uuid.UUID
		productID, _ = uuid.Parse(_productID)
		request.ProductID = productID
	}
	if _marketplace := ctx.Query("marketplace"); _marketplace != "" {
		var marketplace string
		marketplace = _marketplace
		request.Marketplace = marketplace
	}
	if _status := ctx.Query("status"); _status != "" {
		var status string
		status = _status
		request.Status = status
	}

	var response responseProductsInternalAPISetMarketplaceStatus
	if response, err = http.setMarketplaceStatus(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
