// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/internal/transport/jsonRPC/internalapi/viewer"
	"github.com/mbatimel/AMC/products/pkg/interfaces/internalAPI"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerProductsInternalAPI struct {
	next internalAPI.ProductsInternalAPI
}

func loggerMiddlewareProductsInternalAPI() MiddlewareProductsInternalAPI {
	return func(next internalAPI.ProductsInternalAPI) internalAPI.ProductsInternalAPI {
		return &loggerProductsInternalAPI{next: next}
	}
}

func (m loggerProductsInternalAPI) SetMarketplaceStatus(ctx context.Context, productID uuid.UUID, marketplace string, status string) (ok bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsInternalAPI").Str("method", "setMarketplaceStatus").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsInternalAPI.setMarketplaceStatus",
				"request": viewer.Sprintf("%+v", requestProductsInternalAPISetMarketplaceStatus{
					Marketplace: marketplace,
					ProductID:   productID,
					Status:      status,
				}),
				"response": viewer.Sprintf("%+v", responseProductsInternalAPISetMarketplaceStatus{Ok: ok}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call setMarketplaceStatus")
			return
		}
		logger.Info().Func(logHandle).Msg("call setMarketplaceStatus")
	}(time.Now())
	return m.next.SetMarketplaceStatus(ctx, productID, marketplace, status)
}
