// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"strconv"
	"time"

	v2 "github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/interfaces/internalAPI"
)

type metricsProductsInternalAPI struct {
	next internalAPI.ProductsInternalAPI
}

func metricsMiddlewareProductsInternalAPI(next internalAPI.ProductsInternalAPI) internalAPI.ProductsInternalAPI {
	return &metricsProductsInternalAPI{next: next}
}

func (m metricsProductsInternalAPI) SetMarketplaceStatus(ctx context.Context, productID uuid.UUID, marketplace string, status string) (ok bool, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("productsInternalAPI", "setMarketplaceStatus", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("productsInternalAPI", "setMarketplaceStatus", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("productsInternalAPI", "setMarketplaceStatus", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.SetMarketplaceStatus(ctx, productID, marketplace, status)
}
