// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import "github.com/google/uuid"

type requestProductsInternalAPISetMarketplaceStatus struct {
	ProductID   uuid.UUID `json:"productID,omitempty"`
	Marketplace string    `json:"marketplace,omitempty"`
	Status      string    `json:"status,omitempty"`
}

type responseProductsInternalAPISetMarketplaceStatus struct {
	Ok bool `json:"ok,omitempty"`
}
