// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/interfaces/internalAPI"
)

type ProductsInternalAPISetMarketplaceStatus func(ctx context.Context, productID uuid.UUID, marketplace string, status string) (ok bool, err error)

type MiddlewareProductsInternalAPI func(next internalAPI.ProductsInternalAPI) internalAPI.ProductsInternalAPI

type MiddlewareProductsInternalAPISetMarketplaceStatus func(next ProductsInternalAPISetMarketplaceStatus) ProductsInternalAPISetMarketplaceStatus
