// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/products/pkg/interfaces/internalAPI"
)

type httpProductsInternalAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverProductsInternalAPI
	base             internalAPI.ProductsInternalAPI
}

func NewProductsInternalAPI(svcProductsInternalAPI internalAPI.ProductsInternalAPI) (srv *httpProductsInternalAPI) {

	srv = &httpProductsInternalAPI{
		base: svcProductsInternalAPI,
		svc:  newServerProductsInternalAPI(svcProductsInternalAPI),
	}
	return
}

func (http *httpProductsInternalAPI) Service() *serverProductsInternalAPI {
	return http.svc
}

func (http *httpProductsInternalAPI) WithLog() *httpProductsInternalAPI {
	http.svc.WithLog()
	return http
}

func (http *httpProductsInternalAPI) WithMetrics() *httpProductsInternalAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpProductsInternalAPI) WithErrorHandler(handler ErrorHandler) *httpProductsInternalAPI {
	http.errorHandler = handler
	return http
}

func (http *httpProductsInternalAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/products/marketplace-status", http.serveSetMarketplaceStatus)
}
