// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/products/pkg/models"
)

type ProductsAPICreateProduct func(ctx context.Context, userID uuid.UUID, sku string, name string, description string, categoryID uuid.UUID, brandID uuid.UUID, gost string, material string, size string, packageQty int, stockQty int, basePrice float64, clientPrice float64, discountPercent float64, images []models.ProductImage, isPublished bool) (response models.CreateProductResponse, err error)
type ProductsAPIGetProduct func(ctx context.Context, productID uuid.UUID) (response models.GetProductResponse, err error)
type ProductsAPIListProducts func(ctx context.Context, q *string, categoryID *string, brandID *string, material *string, size *string, gost *string, inStock *bool, limit *int, offset *int, sort *string) (response models.ListProductsResponse, err error)
type ProductsAPIUpdateProduct func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, sku *string, name *string, description *string, categoryID *uuid.UUID, brandID *uuid.UUID, gost *string, material *string, size *string, packageQty *int, stockQty *int, basePrice *float64, clientPrice *float64, discountPercent *float64, images *[]models.ProductImage, isPublished *bool) (response models.UpdateProductResponse, err error)
type ProductsAPIDeleteProduct func(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (response models.DeleteProductResponse, err error)
type ProductsAPIListCategories func(ctx context.Context, limit *int, offset *int) (response models.ListCategoriesResponse, err error)
type ProductsAPIListBrands func(ctx context.Context, limit *int, offset *int) (response models.ListBrandsResponse, err error)
type ProductsAPICreatePromotion func(ctx context.Context, userID uuid.UUID, name string, discountPercent float64, startsAt string, endsAt string, products []models.PromotionProduct) (response models.CreatePromotionResponse, err error)
type ProductsAPIGetPromotion func(ctx context.Context, promotionID uuid.UUID) (response models.GetPromotionResponse, err error)
type ProductsAPIListPromotions func(ctx context.Context, limit *int, offset *int) (response models.ListPromotionsResponse, err error)
type ProductsAPIUpdatePromotion func(ctx context.Context, userID uuid.UUID, promotionID uuid.UUID, name string, discountPercent float64, startsAt string, endsAt string, products []models.PromotionProduct) (response models.UpdatePromotionResponse, err error)
type ProductsAPIDeletePromotion func(ctx context.Context, userID uuid.UUID, promotionID uuid.UUID) (response models.DeletePromotionResponse, err error)

type MiddlewareProductsAPI func(next externalapi.ProductsAPI) externalapi.ProductsAPI

type MiddlewareProductsAPICreateProduct func(next ProductsAPICreateProduct) ProductsAPICreateProduct
type MiddlewareProductsAPIGetProduct func(next ProductsAPIGetProduct) ProductsAPIGetProduct
type MiddlewareProductsAPIListProducts func(next ProductsAPIListProducts) ProductsAPIListProducts
type MiddlewareProductsAPIUpdateProduct func(next ProductsAPIUpdateProduct) ProductsAPIUpdateProduct
type MiddlewareProductsAPIDeleteProduct func(next ProductsAPIDeleteProduct) ProductsAPIDeleteProduct
type MiddlewareProductsAPIListCategories func(next ProductsAPIListCategories) ProductsAPIListCategories
type MiddlewareProductsAPIListBrands func(next ProductsAPIListBrands) ProductsAPIListBrands
type MiddlewareProductsAPICreatePromotion func(next ProductsAPICreatePromotion) ProductsAPICreatePromotion
type MiddlewareProductsAPIGetPromotion func(next ProductsAPIGetPromotion) ProductsAPIGetPromotion
type MiddlewareProductsAPIListPromotions func(next ProductsAPIListPromotions) ProductsAPIListPromotions
type MiddlewareProductsAPIUpdatePromotion func(next ProductsAPIUpdatePromotion) ProductsAPIUpdatePromotion
type MiddlewareProductsAPIDeletePromotion func(next ProductsAPIDeletePromotion) ProductsAPIDeletePromotion
