// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/models"
)

type requestProductsAPICreateProduct struct {
	UserID          uuid.UUID             `json:"userID,omitempty"`
	Sku             string                `json:"sku,omitempty"`
	Name            string                `json:"name,omitempty"`
	Description     string                `json:"description,omitempty"`
	CategoryID      uuid.UUID             `json:"categoryID,omitempty"`
	BrandID         uuid.UUID             `json:"brandID,omitempty"`
	Gost            string                `json:"gost,omitempty"`
	Material        string                `json:"material,omitempty"`
	Size            string                `json:"size,omitempty"`
	PackageQty      int                   `json:"packageQty,omitempty"`
	StockQty        int                   `json:"stockQty,omitempty"`
	BasePrice       float64               `json:"basePrice,omitempty"`
	ClientPrice     float64               `json:"clientPrice,omitempty"`
	DiscountPercent float64               `json:"discountPercent,omitempty"`
	Images          []models.ProductImage `json:"images,omitempty"`
	IsPublished     bool                  `json:"isPublished,omitempty"`
}

type responseProductsAPICreateProduct struct {
	Response models.CreateProductResponse `json:"response,omitempty"`
}

type requestProductsAPIGetProduct struct {
	ProductID uuid.UUID `json:"productID,omitempty"`
}

type responseProductsAPIGetProduct struct {
	Response models.GetProductResponse `json:"response,omitempty"`
}

type requestProductsAPIListProducts struct {
	Q          *string `json:"q,omitempty"`
	CategoryID *string `json:"categoryID,omitempty"`
	BrandID    *string `json:"brandID,omitempty"`
	Material   *string `json:"material,omitempty"`
	Size       *string `json:"size,omitempty"`
	Gost       *string `json:"gost,omitempty"`
	InStock    *bool   `json:"inStock,omitempty"`
	Limit      *int    `json:"limit,omitempty"`
	Offset     *int    `json:"offset,omitempty"`
	Sort       *string `json:"sort,omitempty"`
}

type responseProductsAPIListProducts struct {
	Response models.ListProductsResponse `json:"response,omitempty"`
}

type requestProductsAPIUpdateProduct struct {
	UserID          uuid.UUID              `json:"userID,omitempty"`
	ProductID       uuid.UUID              `json:"productID,omitempty"`
	Sku             *string                `json:"sku,omitempty"`
	Name            *string                `json:"name,omitempty"`
	Description     *string                `json:"description,omitempty"`
	CategoryID      *uuid.UUID             `json:"categoryID,omitempty"`
	BrandID         *uuid.UUID             `json:"brandID,omitempty"`
	Gost            *string                `json:"gost,omitempty"`
	Material        *string                `json:"material,omitempty"`
	Size            *string                `json:"size,omitempty"`
	PackageQty      *int                   `json:"packageQty,omitempty"`
	StockQty        *int                   `json:"stockQty,omitempty"`
	BasePrice       *float64               `json:"basePrice,omitempty"`
	ClientPrice     *float64               `json:"clientPrice,omitempty"`
	DiscountPercent *float64               `json:"discountPercent,omitempty"`
	Images          *[]models.ProductImage `json:"images,omitempty"`
	IsPublished     *bool                  `json:"isPublished,omitempty"`
}

type responseProductsAPIUpdateProduct struct {
	Response models.UpdateProductResponse `json:"response,omitempty"`
}

type requestProductsAPIDeleteProduct struct {
	UserID    uuid.UUID `json:"userID,omitempty"`
	ProductID uuid.UUID `json:"productID,omitempty"`
}

type responseProductsAPIDeleteProduct struct {
	Response models.DeleteProductResponse `json:"response,omitempty"`
}

type requestProductsAPIListCategories struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type responseProductsAPIListCategories struct {
	Response models.ListCategoriesResponse `json:"response,omitempty"`
}

type requestProductsAPIListBrands struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type responseProductsAPIListBrands struct {
	Response models.ListBrandsResponse `json:"response,omitempty"`
}
