// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
	customhandlers "github.com/mbatimel/AMC/products/internal/transport/custom-handlers"
)

func (http *httpProductsAPI) createProduct(ctx context.Context, request requestProductsAPICreateProduct) (response responseProductsAPICreateProduct, err error) {

	response.Response, err = http.svc.CreateProduct(ctx, request.UserID, request.Sku, request.Name, request.Description, request.CategoryID, request.BrandID, request.Gost, request.Material, request.Size, request.PackageQty, request.StockQty, request.BasePrice, request.ClientPrice, request.DiscountPercent, request.Images, request.IsPublished)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveCreateProduct(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPICreateProduct
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.CreateProduct(ctx, http.svc, request.UserID, request.Sku, request.Name, request.Description, request.CategoryID, request.BrandID, request.Gost, request.Material, request.Size, request.PackageQty, request.StockQty, request.BasePrice, request.ClientPrice, request.DiscountPercent, request.Images, request.IsPublished)
}
func (http *httpProductsAPI) getProduct(ctx context.Context, request requestProductsAPIGetProduct) (response responseProductsAPIGetProduct, err error) {

	response.Response, err = http.svc.GetProduct(ctx, request.ProductID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveGetProduct(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIGetProduct

	if _productID := ctx.Params("productID"); _productID != "" {
		var productID uuid.UUID
		productID, _ = uuid.Parse(_productID)
		request.ProductID = productID
	}

	return customhandlers.GetProduct(ctx, http.svc, request.ProductID)
}
func (http *httpProductsAPI) listProducts(ctx context.Context, request requestProductsAPIListProducts) (response responseProductsAPIListProducts, err error) {

	response.Response, err = http.svc.ListProducts(ctx, request.Q, request.CategoryID, request.BrandID, request.Material, request.Size, request.Gost, request.InStock, request.Limit, request.Offset, request.Sort)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveListProducts(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIListProducts

	if _limit := ctx.Query("limit"); _limit != "" {
		var limit int
		limit, err = strconv.Atoi(_limit)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = &limit
	}
	if _offset := ctx.Query("offset"); _offset != "" {
		var offset int
		offset, err = strconv.Atoi(_offset)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = &offset
	}
	if _sort := ctx.Query("sort"); _sort != "" {
		var sort string
		sort = _sort
		request.Sort = &sort
	}
	if _q := ctx.Query("q"); _q != "" {
		var q string
		q = _q
		request.Q = &q
	}
	if _material := ctx.Query("material"); _material != "" {
		var material string
		material = _material
		request.Material = &material
	}
	if _size := ctx.Query("size"); _size != "" {
		var size string
		size = _size
		request.Size = &size
	}
	if _inStock := ctx.Query("inStock"); _inStock != "" {
		var inStock bool
		inStock, err = strconv.ParseBool(_inStock)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.InStock = &inStock
	}
	if _categoryID := ctx.Query("categoryID"); _categoryID != "" {
		var categoryID string
		categoryID = _categoryID
		request.CategoryID = &categoryID
	}
	if _brandID := ctx.Query("brandID"); _brandID != "" {
		var brandID string
		brandID = _brandID
		request.BrandID = &brandID
	}
	if _gost := ctx.Query("gost"); _gost != "" {
		var gost string
		gost = _gost
		request.Gost = &gost
	}

	return customhandlers.ListProducts(ctx, http.svc, request.Q, request.CategoryID, request.BrandID, request.Material, request.Size, request.Gost, request.InStock, request.Limit, request.Offset, request.Sort)
}
func (http *httpProductsAPI) updateProduct(ctx context.Context, request requestProductsAPIUpdateProduct) (response responseProductsAPIUpdateProduct, err error) {

	response.Response, err = http.svc.UpdateProduct(ctx, request.UserID, request.ProductID, request.Sku, request.Name, request.Description, request.CategoryID, request.BrandID, request.Gost, request.Material, request.Size, request.PackageQty, request.StockQty, request.BasePrice, request.ClientPrice, request.DiscountPercent, request.Images, request.IsPublished)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveUpdateProduct(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIUpdateProduct
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _productID := ctx.Params("productID"); _productID != "" {
		var productID uuid.UUID
		productID, _ = uuid.Parse(_productID)
		request.ProductID = productID
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.UpdateProduct(ctx, http.svc, request.UserID, request.ProductID, request.Sku, request.Name, request.Description, request.CategoryID, request.BrandID, request.Gost, request.Material, request.Size, request.PackageQty, request.StockQty, request.BasePrice, request.ClientPrice, request.DiscountPercent, request.Images, request.IsPublished)
}
func (http *httpProductsAPI) deleteProduct(ctx context.Context, request requestProductsAPIDeleteProduct) (response responseProductsAPIDeleteProduct, err error) {

	response.Response, err = http.svc.DeleteProduct(ctx, request.UserID, request.ProductID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveDeleteProduct(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIDeleteProduct

	if _productID := ctx.Params("productID"); _productID != "" {
		var productID uuid.UUID
		productID, _ = uuid.Parse(_productID)
		request.ProductID = productID
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	return customhandlers.DeleteProduct(ctx, http.svc, request.UserID, request.ProductID)
}
func (http *httpProductsAPI) listCategories(ctx context.Context, request requestProductsAPIListCategories) (response responseProductsAPIListCategories, err error) {

	response.Response, err = http.svc.ListCategories(ctx, request.Limit, request.Offset)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveListCategories(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIListCategories

	if _limit := ctx.Query("limit"); _limit != "" {
		var limit int
		limit, err = strconv.Atoi(_limit)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = &limit
	}
	if _offset := ctx.Query("offset"); _offset != "" {
		var offset int
		offset, err = strconv.Atoi(_offset)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = &offset
	}

	return customhandlers.ListCategories(ctx, http.svc, request.Limit, request.Offset)
}
func (http *httpProductsAPI) listBrands(ctx context.Context, request requestProductsAPIListBrands) (response responseProductsAPIListBrands, err error) {

	response.Response, err = http.svc.ListBrands(ctx, request.Limit, request.Offset)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpProductsAPI) serveListBrands(ctx *fiber.Ctx) (err error) {

	var request requestProductsAPIListBrands

	if _limit := ctx.Query("limit"); _limit != "" {
		var limit int
		limit, err = strconv.Atoi(_limit)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Limit = &limit
	}
	if _offset := ctx.Query("offset"); _offset != "" {
		var offset int
		offset, err = strconv.Atoi(_offset)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Offset = &offset
	}

	return customhandlers.ListBrands(ctx, http.svc, request.Limit, request.Offset)
}
