// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/products/pkg/models"
)

type serverProductsAPI struct {
	svc             externalapi.ProductsAPI
	createProduct   ProductsAPICreateProduct
	getProduct      ProductsAPIGetProduct
	listProducts    ProductsAPIListProducts
	updateProduct   ProductsAPIUpdateProduct
	deleteProduct   ProductsAPIDeleteProduct
	listCategories  ProductsAPIListCategories
	listBrands      ProductsAPIListBrands
	createPromotion ProductsAPICreatePromotion
	getPromotion    ProductsAPIGetPromotion
	listPromotions  ProductsAPIListPromotions
	updatePromotion ProductsAPIUpdatePromotion
	deletePromotion ProductsAPIDeletePromotion
}

type MiddlewareSetProductsAPI interface {
	Wrap(m MiddlewareProductsAPI)
	WrapCreateProduct(m MiddlewareProductsAPICreateProduct)
	WrapGetProduct(m MiddlewareProductsAPIGetProduct)
	WrapListProducts(m MiddlewareProductsAPIListProducts)
	WrapUpdateProduct(m MiddlewareProductsAPIUpdateProduct)
	WrapDeleteProduct(m MiddlewareProductsAPIDeleteProduct)
	WrapListCategories(m MiddlewareProductsAPIListCategories)
	WrapListBrands(m MiddlewareProductsAPIListBrands)
	WrapCreatePromotion(m MiddlewareProductsAPICreatePromotion)
	WrapGetPromotion(m MiddlewareProductsAPIGetPromotion)
	WrapListPromotions(m MiddlewareProductsAPIListPromotions)
	WrapUpdatePromotion(m MiddlewareProductsAPIUpdatePromotion)
	WrapDeletePromotion(m MiddlewareProductsAPIDeletePromotion)

	WithMetrics()
	WithLog()
}

func newServerProductsAPI(svc externalapi.ProductsAPI) *serverProductsAPI {
	return &serverProductsAPI{
		createProduct:   svc.CreateProduct,
		createPromotion: svc.CreatePromotion,
		deleteProduct:   svc.DeleteProduct,
		deletePromotion: svc.DeletePromotion,
		getProduct:      svc.GetProduct,
		getPromotion:    svc.GetPromotion,
		listBrands:      svc.ListBrands,
		listCategories:  svc.ListCategories,
		listProducts:    svc.ListProducts,
		listPromotions:  svc.ListPromotions,
		svc:             svc,
		updateProduct:   svc.UpdateProduct,
		updatePromotion: svc.UpdatePromotion,
	}
}

func (srv *serverProductsAPI) Wrap(m MiddlewareProductsAPI) {
	srv.svc = m(srv.svc)
	srv.createProduct = srv.svc.CreateProduct
	srv.getProduct = srv.svc.GetProduct
	srv.listProducts = srv.svc.ListProducts
	srv.updateProduct = srv.svc.UpdateProduct
	srv.deleteProduct = srv.svc.DeleteProduct
	srv.listCategories = srv.svc.ListCategories
	srv.listBrands = srv.svc.ListBrands
	srv.createPromotion = srv.svc.CreatePromotion
	srv.getPromotion = srv.svc.GetPromotion
	srv.listPromotions = srv.svc.ListPromotions
	srv.updatePromotion = srv.svc.UpdatePromotion
	srv.deletePromotion = srv.svc.DeletePromotion
}

func (srv *serverProductsAPI) CreateProduct(ctx context.Context, userID uuid.UUID, sku string, name string, description string, categoryID uuid.UUID, brandID uuid.UUID, gost string, material string, size string, packageQty int, stockQty int, basePrice float64, clientPrice float64, discountPercent float64, images []models.ProductImage, isPublished bool) (response models.CreateProductResponse, err error) {
	return srv.createProduct(ctx, userID, sku, name, description, categoryID, brandID, gost, material, size, packageQty, stockQty, basePrice, clientPrice, discountPercent, images, isPublished)
}

func (srv *serverProductsAPI) GetProduct(ctx context.Context, productID uuid.UUID) (response models.GetProductResponse, err error) {
	return srv.getProduct(ctx, productID)
}

func (srv *serverProductsAPI) ListProducts(ctx context.Context, q *string, categoryID *string, brandID *string, material *string, size *string, gost *string, inStock *bool, limit *int, offset *int, sort *string) (response models.ListProductsResponse, err error) {
	return srv.listProducts(ctx, q, categoryID, brandID, material, size, gost, inStock, limit, offset, sort)
}

func (srv *serverProductsAPI) UpdateProduct(ctx context.Context, userID uuid.UUID, productID uuid.UUID, sku *string, name *string, description *string, categoryID *uuid.UUID, brandID *uuid.UUID, gost *string, material *string, size *string, packageQty *int, stockQty *int, basePrice *float64, clientPrice *float64, discountPercent *float64, images *[]models.ProductImage, isPublished *bool) (response models.UpdateProductResponse, err error) {
	return srv.updateProduct(ctx, userID, productID, sku, name, description, categoryID, brandID, gost, material, size, packageQty, stockQty, basePrice, clientPrice, discountPercent, images, isPublished)
}

func (srv *serverProductsAPI) DeleteProduct(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (response models.DeleteProductResponse, err error) {
	return srv.deleteProduct(ctx, userID, productID)
}

func (srv *serverProductsAPI) ListCategories(ctx context.Context, limit *int, offset *int) (response models.ListCategoriesResponse, err error) {
	return srv.listCategories(ctx, limit, offset)
}

func (srv *serverProductsAPI) ListBrands(ctx context.Context, limit *int, offset *int) (response models.ListBrandsResponse, err error) {
	return srv.listBrands(ctx, limit, offset)
}

func (srv *serverProductsAPI) CreatePromotion(ctx context.Context, userID uuid.UUID, name string, discountPercent float64, startsAt string, endsAt string, products []models.PromotionProduct) (response models.CreatePromotionResponse, err error) {
	return srv.createPromotion(ctx, userID, name, discountPercent, startsAt, endsAt, products)
}

func (srv *serverProductsAPI) GetPromotion(ctx context.Context, promotionID uuid.UUID) (response models.GetPromotionResponse, err error) {
	return srv.getPromotion(ctx, promotionID)
}

func (srv *serverProductsAPI) ListPromotions(ctx context.Context, limit *int, offset *int) (response models.ListPromotionsResponse, err error) {
	return srv.listPromotions(ctx, limit, offset)
}

func (srv *serverProductsAPI) UpdatePromotion(ctx context.Context, userID uuid.UUID, promotionID uuid.UUID, name string, discountPercent float64, startsAt string, endsAt string, products []models.PromotionProduct) (response models.UpdatePromotionResponse, err error) {
	return srv.updatePromotion(ctx, userID, promotionID, name, discountPercent, startsAt, endsAt, products)
}

func (srv *serverProductsAPI) DeletePromotion(ctx context.Context, userID uuid.UUID, promotionID uuid.UUID) (response models.DeletePromotionResponse, err error) {
	return srv.deletePromotion(ctx, userID, promotionID)
}

func (srv *serverProductsAPI) WrapCreateProduct(m MiddlewareProductsAPICreateProduct) {
	srv.createProduct = m(srv.createProduct)
}

func (srv *serverProductsAPI) WrapGetProduct(m MiddlewareProductsAPIGetProduct) {
	srv.getProduct = m(srv.getProduct)
}

func (srv *serverProductsAPI) WrapListProducts(m MiddlewareProductsAPIListProducts) {
	srv.listProducts = m(srv.listProducts)
}

func (srv *serverProductsAPI) WrapUpdateProduct(m MiddlewareProductsAPIUpdateProduct) {
	srv.updateProduct = m(srv.updateProduct)
}

func (srv *serverProductsAPI) WrapDeleteProduct(m MiddlewareProductsAPIDeleteProduct) {
	srv.deleteProduct = m(srv.deleteProduct)
}

func (srv *serverProductsAPI) WrapListCategories(m MiddlewareProductsAPIListCategories) {
	srv.listCategories = m(srv.listCategories)
}

func (srv *serverProductsAPI) WrapListBrands(m MiddlewareProductsAPIListBrands) {
	srv.listBrands = m(srv.listBrands)
}

func (srv *serverProductsAPI) WrapCreatePromotion(m MiddlewareProductsAPICreatePromotion) {
	srv.createPromotion = m(srv.createPromotion)
}

func (srv *serverProductsAPI) WrapGetPromotion(m MiddlewareProductsAPIGetPromotion) {
	srv.getPromotion = m(srv.getPromotion)
}

func (srv *serverProductsAPI) WrapListPromotions(m MiddlewareProductsAPIListPromotions) {
	srv.listPromotions = m(srv.listPromotions)
}

func (srv *serverProductsAPI) WrapUpdatePromotion(m MiddlewareProductsAPIUpdatePromotion) {
	srv.updatePromotion = m(srv.updatePromotion)
}

func (srv *serverProductsAPI) WrapDeletePromotion(m MiddlewareProductsAPIDeletePromotion) {
	srv.deletePromotion = m(srv.deletePromotion)
}

func (srv *serverProductsAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareProductsAPI)
}

func (srv *serverProductsAPI) WithLog() {
	srv.Wrap(loggerMiddlewareProductsAPI())
}
