// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/mbatimel/AMC/products/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/AMC/products/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/products/pkg/models"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerProductsAPI struct {
	next externalapi.ProductsAPI
}

func loggerMiddlewareProductsAPI() MiddlewareProductsAPI {
	return func(next externalapi.ProductsAPI) externalapi.ProductsAPI {
		return &loggerProductsAPI{next: next}
	}
}

func (m loggerProductsAPI) CreateProduct(ctx context.Context, sku string, name string, description string, categoryID string, brandID string, gost string, material string, size string, packageQty int, stockQty int, basePrice float64, clientPrice float64, discountPercent float64, isPublished bool) (response models.CreateProductResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "createProduct").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsAPI.createProduct",
				"request": viewer.Sprintf("%+v", requestProductsAPICreateProduct{
					BasePrice:       basePrice,
					BrandID:         brandID,
					CategoryID:      categoryID,
					ClientPrice:     clientPrice,
					Description:     description,
					DiscountPercent: discountPercent,
					Gost:            gost,
					IsPublished:     isPublished,
					Material:        material,
					Name:            name,
					PackageQty:      packageQty,
					Size:            size,
					Sku:             sku,
					StockQty:        stockQty,
				}),
				"response": viewer.Sprintf("%+v", responseProductsAPICreateProduct{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createProduct")
			return
		}
		logger.Info().Func(logHandle).Msg("call createProduct")
	}(time.Now())
	return m.next.CreateProduct(ctx, sku, name, description, categoryID, brandID, gost, material, size, packageQty, stockQty, basePrice, clientPrice, discountPercent, isPublished)
}

func (m loggerProductsAPI) GetProduct(ctx context.Context, productID string) (response models.GetProductResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "getProduct").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "productsAPI.getProduct",
				"request":  viewer.Sprintf("%+v", requestProductsAPIGetProduct{ProductID: productID}),
				"response": viewer.Sprintf("%+v", responseProductsAPIGetProduct{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getProduct")
			return
		}
		logger.Info().Func(logHandle).Msg("call getProduct")
	}(time.Now())
	return m.next.GetProduct(ctx, productID)
}

func (m loggerProductsAPI) ListProducts(ctx context.Context, q string, categoryID string, brandID string, material string, size string, gost string, inStock bool, limit int, offset int, sort string) (response models.ListProductsResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "listProducts").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsAPI.listProducts",
				"request": viewer.Sprintf("%+v", requestProductsAPIListProducts{
					BrandID:    brandID,
					CategoryID: categoryID,
					Gost:       gost,
					InStock:    inStock,
					Limit:      limit,
					Material:   material,
					Offset:     offset,
					Q:          q,
					Size:       size,
					Sort:       sort,
				}),
				"response": viewer.Sprintf("%+v", responseProductsAPIListProducts{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listProducts")
			return
		}
		logger.Info().Func(logHandle).Msg("call listProducts")
	}(time.Now())
	return m.next.ListProducts(ctx, q, categoryID, brandID, material, size, gost, inStock, limit, offset, sort)
}

func (m loggerProductsAPI) UpdateProduct(ctx context.Context, productID string, sku string, name string, description string, categoryID string, brandID string, gost string, material string, size string, packageQty int, stockQty int, basePrice float64, clientPrice float64, discountPercent float64, isPublished bool) (response models.UpdateProductResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "updateProduct").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsAPI.updateProduct",
				"request": viewer.Sprintf("%+v", requestProductsAPIUpdateProduct{
					BasePrice:       basePrice,
					BrandID:         brandID,
					CategoryID:      categoryID,
					ClientPrice:     clientPrice,
					Description:     description,
					DiscountPercent: discountPercent,
					Gost:            gost,
					IsPublished:     isPublished,
					Material:        material,
					Name:            name,
					PackageQty:      packageQty,
					ProductID:       productID,
					Size:            size,
					Sku:             sku,
					StockQty:        stockQty,
				}),
				"response": viewer.Sprintf("%+v", responseProductsAPIUpdateProduct{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateProduct")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateProduct")
	}(time.Now())
	return m.next.UpdateProduct(ctx, productID, sku, name, description, categoryID, brandID, gost, material, size, packageQty, stockQty, basePrice, clientPrice, discountPercent, isPublished)
}

func (m loggerProductsAPI) DeleteProduct(ctx context.Context, productID string) (response models.DeleteProductResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "deleteProduct").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "productsAPI.deleteProduct",
				"request":  viewer.Sprintf("%+v", requestProductsAPIDeleteProduct{ProductID: productID}),
				"response": viewer.Sprintf("%+v", responseProductsAPIDeleteProduct{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteProduct")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteProduct")
	}(time.Now())
	return m.next.DeleteProduct(ctx, productID)
}

func (m loggerProductsAPI) ListCategories(ctx context.Context, limit int, offset int) (response models.ListCategoriesResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "listCategories").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsAPI.listCategories",
				"request": viewer.Sprintf("%+v", requestProductsAPIListCategories{
					Limit:  limit,
					Offset: offset,
				}),
				"response": viewer.Sprintf("%+v", responseProductsAPIListCategories{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listCategories")
			return
		}
		logger.Info().Func(logHandle).Msg("call listCategories")
	}(time.Now())
	return m.next.ListCategories(ctx, limit, offset)
}

func (m loggerProductsAPI) ListBrands(ctx context.Context, limit int, offset int) (response models.ListBrandsResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ProductsAPI").Str("method", "listBrands").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "productsAPI.listBrands",
				"request": viewer.Sprintf("%+v", requestProductsAPIListBrands{
					Limit:  limit,
					Offset: offset,
				}),
				"response": viewer.Sprintf("%+v", responseProductsAPIListBrands{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listBrands")
			return
		}
		logger.Info().Func(logHandle).Msg("call listBrands")
	}(time.Now())
	return m.next.ListBrands(ctx, limit, offset)
}
