// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type httpAuthAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverAuthAPI
	base             externalAPI.AuthAPI
}

func NewAuthAPI(svcAuthAPI externalAPI.AuthAPI) (srv *httpAuthAPI) {

	srv = &httpAuthAPI{
		base: svcAuthAPI,
		svc:  newServerAuthAPI(svcAuthAPI),
	}
	return
}

func (http *httpAuthAPI) Service() *serverAuthAPI {
	return http.svc
}

func (http *httpAuthAPI) WithLog() *httpAuthAPI {
	http.svc.WithLog()
	return http
}

func (http *httpAuthAPI) WithMetrics() *httpAuthAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpAuthAPI) WithErrorHandler(handler ErrorHandler) *httpAuthAPI {
	http.errorHandler = handler
	return http
}

func (http *httpAuthAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/auth/login", http.serveLoginUser)
	route.Post("/api/v1/auth/register/ip", http.serveRegisterIP)
	route.Post("/api/v1/auth/register/individual", http.serveRegisterIndividual)
	route.Post("/api/v1/auth/logout", http.serveLogoutUser)
	route.Post("/api/v1/auth/change-password", http.serveChangePassword)
	route.Post("/api/v1/auth/verify-email", http.serveVerifyEmailCode)
	route.Post("/api/v1/auth/send-verification", http.serveSendEmailVerification)
}
