// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type AuthAPILoginUser func(ctx context.Context, email string, password string) (userID uuid.UUID, err error)
type AuthAPILogoutUser func(ctx context.Context, userID uuid.UUID) (err error)
type AuthAPIChangePassword func(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error)
type AuthAPIVerifyEmailCode func(ctx context.Context, userID uuid.UUID, code int64) (err error)
type AuthAPISendEmailVerification func(ctx context.Context, userID uuid.UUID) (err error)
type AuthAPIRequestPasswordReset func(ctx context.Context, email string) (emailSent bool, err error)
type AuthAPIConfirmPasswordReset func(ctx context.Context, token string, newPassword string) (err error)

type MiddlewareAuthAPI func(next externalAPI.AuthAPI) externalAPI.AuthAPI

type MiddlewareAuthAPILoginUser func(next AuthAPILoginUser) AuthAPILoginUser
type MiddlewareAuthAPILogoutUser func(next AuthAPILogoutUser) AuthAPILogoutUser
type MiddlewareAuthAPIChangePassword func(next AuthAPIChangePassword) AuthAPIChangePassword
type MiddlewareAuthAPIVerifyEmailCode func(next AuthAPIVerifyEmailCode) AuthAPIVerifyEmailCode
type MiddlewareAuthAPISendEmailVerification func(next AuthAPISendEmailVerification) AuthAPISendEmailVerification
type MiddlewareAuthAPIRequestPasswordReset func(next AuthAPIRequestPasswordReset) AuthAPIRequestPasswordReset
type MiddlewareAuthAPIConfirmPasswordReset func(next AuthAPIConfirmPasswordReset) AuthAPIConfirmPasswordReset
