// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type serverAuthAPI struct {
	svc                   externalAPI.AuthAPI
	loginUser             AuthAPILoginUser
	registerIP            AuthAPIRegisterIP
	registerIndividual    AuthAPIRegisterIndividual
	logoutUser            AuthAPILogoutUser
	changePassword        AuthAPIChangePassword
	verifyEmailCode       AuthAPIVerifyEmailCode
	sendEmailVerification AuthAPISendEmailVerification
}

type MiddlewareSetAuthAPI interface {
	Wrap(m MiddlewareAuthAPI)
	WrapLoginUser(m MiddlewareAuthAPILoginUser)
	WrapRegisterIP(m MiddlewareAuthAPIRegisterIP)
	WrapRegisterIndividual(m MiddlewareAuthAPIRegisterIndividual)
	WrapLogoutUser(m MiddlewareAuthAPILogoutUser)
	WrapChangePassword(m MiddlewareAuthAPIChangePassword)
	WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode)
	WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification)

	WithMetrics()
	WithLog()
}

func newServerAuthAPI(svc externalAPI.AuthAPI) *serverAuthAPI {
	return &serverAuthAPI{
		changePassword:        svc.ChangePassword,
		loginUser:             svc.LoginUser,
		logoutUser:            svc.LogoutUser,
		registerIP:            svc.RegisterIP,
		registerIndividual:    svc.RegisterIndividual,
		sendEmailVerification: svc.SendEmailVerification,
		svc:                   svc,
		verifyEmailCode:       svc.VerifyEmailCode,
	}
}

func (srv *serverAuthAPI) Wrap(m MiddlewareAuthAPI) {
	srv.svc = m(srv.svc)
	srv.loginUser = srv.svc.LoginUser
	srv.registerIP = srv.svc.RegisterIP
	srv.registerIndividual = srv.svc.RegisterIndividual
	srv.logoutUser = srv.svc.LogoutUser
	srv.changePassword = srv.svc.ChangePassword
	srv.verifyEmailCode = srv.svc.VerifyEmailCode
	srv.sendEmailVerification = srv.svc.SendEmailVerification
}

func (srv *serverAuthAPI) LoginUser(ctx context.Context, email string, password string) (userID uuid.UUID, err error) {
	return srv.loginUser(ctx, email, password)
}

func (srv *serverAuthAPI) RegisterIP(ctx context.Context, email string, password string, fullName *string, shortName *string, inn *string, kpp *string, ogrn *string, okved *string, taxSystem *string, legalAddress *string, actualAddress *string, directorFullName *string, directorPosition *string, phone *string, additionalPhone *string, website *string, bankAccount *string, bankName *string, bankBik *string, correspondentAccount *string) (userID uuid.UUID, err error) {
	return srv.registerIP(ctx, email, password, fullName, shortName, inn, kpp, ogrn, okved, taxSystem, legalAddress, actualAddress, directorFullName, directorPosition, phone, additionalPhone, website, bankAccount, bankName, bankBik, correspondentAccount)
}

func (srv *serverAuthAPI) RegisterIndividual(ctx context.Context, fio string, phone string, email string, deliveryAddress string, password string, city string, inn *string) (userID uuid.UUID, err error) {
	return srv.registerIndividual(ctx, fio, phone, email, deliveryAddress, password, city, inn)
}

func (srv *serverAuthAPI) LogoutUser(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.logoutUser(ctx, userID)
}

func (srv *serverAuthAPI) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error) {
	return srv.changePassword(ctx, userID, oldPassword, newPassword)
}

func (srv *serverAuthAPI) VerifyEmailCode(ctx context.Context, userID uuid.UUID, code int64) (err error) {
	return srv.verifyEmailCode(ctx, userID, code)
}

func (srv *serverAuthAPI) SendEmailVerification(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.sendEmailVerification(ctx, userID)
}

func (srv *serverAuthAPI) WrapLoginUser(m MiddlewareAuthAPILoginUser) {
	srv.loginUser = m(srv.loginUser)
}

func (srv *serverAuthAPI) WrapRegisterIP(m MiddlewareAuthAPIRegisterIP) {
	srv.registerIP = m(srv.registerIP)
}

func (srv *serverAuthAPI) WrapRegisterIndividual(m MiddlewareAuthAPIRegisterIndividual) {
	srv.registerIndividual = m(srv.registerIndividual)
}

func (srv *serverAuthAPI) WrapLogoutUser(m MiddlewareAuthAPILogoutUser) {
	srv.logoutUser = m(srv.logoutUser)
}

func (srv *serverAuthAPI) WrapChangePassword(m MiddlewareAuthAPIChangePassword) {
	srv.changePassword = m(srv.changePassword)
}

func (srv *serverAuthAPI) WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode) {
	srv.verifyEmailCode = m(srv.verifyEmailCode)
}

func (srv *serverAuthAPI) WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification) {
	srv.sendEmailVerification = m(srv.sendEmailVerification)
}

func (srv *serverAuthAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAuthAPI)
}

func (srv *serverAuthAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAuthAPI())
}
