// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import "github.com/google/uuid"

type requestAuthAPILoginUser struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAuthAPILoginUser struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestAuthAPIRegisterIP struct {
	Email                string  `json:"email,omitempty"`
	Password             string  `json:"password,omitempty"`
	FullName             *string `json:"fullName,omitempty"`
	ShortName            *string `json:"shortName,omitempty"`
	Inn                  *string `json:"inn,omitempty"`
	Kpp                  *string `json:"kpp,omitempty"`
	Ogrn                 *string `json:"ogrn,omitempty"`
	Okved                *string `json:"okved,omitempty"`
	TaxSystem            *string `json:"taxSystem,omitempty"`
	LegalAddress         *string `json:"legalAddress,omitempty"`
	ActualAddress        *string `json:"actualAddress,omitempty"`
	DirectorFullName     *string `json:"directorFullName,omitempty"`
	DirectorPosition     *string `json:"directorPosition,omitempty"`
	Phone                *string `json:"phone,omitempty"`
	AdditionalPhone      *string `json:"additionalPhone,omitempty"`
	Website              *string `json:"website,omitempty"`
	BankAccount          *string `json:"bankAccount,omitempty"`
	BankName             *string `json:"bankName,omitempty"`
	BankBik              *string `json:"bankBik,omitempty"`
	CorrespondentAccount *string `json:"correspondentAccount,omitempty"`
}

type responseAuthAPIRegisterIP struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestAuthAPIRegisterIndividual struct {
	Fio             string  `json:"fio,omitempty"`
	Phone           string  `json:"phone,omitempty"`
	Email           string  `json:"email,omitempty"`
	DeliveryAddress string  `json:"deliveryAddress,omitempty"`
	Password        string  `json:"password,omitempty"`
	City            string  `json:"city,omitempty"`
	Inn             *string `json:"inn,omitempty"`
}

type responseAuthAPIRegisterIndividual struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestAuthAPILogoutUser struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPILogoutUser struct{}

type requestAuthAPIChangePassword struct {
	UserID      uuid.UUID `json:"userID,omitempty"`
	OldPassword string    `json:"oldPassword,omitempty"`
	NewPassword string    `json:"newPassword,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPIChangePassword struct{}

type requestAuthAPIVerifyEmailCode struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Code   int64     `json:"code,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPIVerifyEmailCode struct{}

type requestAuthAPISendEmailVerification struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPISendEmailVerification struct{}
