// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import "github.com/google/uuid"

type requestAuthAPILoginUser struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAuthAPILoginUser struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestAuthAPISignUpUser struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
	Name     string `json:"name,omitempty"`
	Surename string `json:"surename,omitempty"`
}

type responseAuthAPISignUpUser struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type requestAuthAPIChangePassword struct {
	UserID      uuid.UUID `json:"userID,omitempty"`
	OldPassword string    `json:"oldPassword,omitempty"`
	NewPassword string    `json:"newPassword,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPIChangePassword struct{}

type requestAuthAPIVerifyEmailCode struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Code   int64     `json:"code,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPIVerifyEmailCode struct{}

type requestAuthAPISendEmailVerification struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAuthAPISendEmailVerification struct{}
