// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
)

func (http *httpAuthAPI) loginUser(ctx context.Context, request requestAuthAPILoginUser) (response responseAuthAPILoginUser, err error) {

	response.UserID, err = http.svc.LoginUser(ctx, request.Email, request.Password)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveLoginUser(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPILoginUser
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseAuthAPILoginUser
	if response, err = http.loginUser(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) registerIP(ctx context.Context, request requestAuthAPIRegisterIP) (response responseAuthAPIRegisterIP, err error) {

	response.UserID, err = http.svc.RegisterIP(ctx, request.Email, request.Password, request.FullName, request.ShortName, request.Inn, request.Kpp, request.Ogrn, request.Okved, request.TaxSystem, request.LegalAddress, request.ActualAddress, request.DirectorFullName, request.DirectorPosition, request.Phone, request.AdditionalPhone, request.Website, request.BankAccount, request.BankName, request.BankBik, request.CorrespondentAccount)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveRegisterIP(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIRegisterIP
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseAuthAPIRegisterIP
	if response, err = http.registerIP(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) registerIndividual(ctx context.Context, request requestAuthAPIRegisterIndividual) (response responseAuthAPIRegisterIndividual, err error) {

	response.UserID, err = http.svc.RegisterIndividual(ctx, request.Fio, request.Phone, request.Email, request.DeliveryAddress, request.Password, request.City, request.Inn)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveRegisterIndividual(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIRegisterIndividual
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseAuthAPIRegisterIndividual
	if response, err = http.registerIndividual(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) logoutUser(ctx context.Context, request requestAuthAPILogoutUser) (response responseAuthAPILogoutUser, err error) {

	err = http.svc.LogoutUser(ctx, request.UserID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveLogoutUser(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPILogoutUser

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPILogoutUser
	if response, err = http.logoutUser(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) changePassword(ctx context.Context, request requestAuthAPIChangePassword) (response responseAuthAPIChangePassword, err error) {

	err = http.svc.ChangePassword(ctx, request.UserID, request.OldPassword, request.NewPassword)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveChangePassword(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIChangePassword
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPIChangePassword
	if response, err = http.changePassword(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) verifyEmailCode(ctx context.Context, request requestAuthAPIVerifyEmailCode) (response responseAuthAPIVerifyEmailCode, err error) {

	err = http.svc.VerifyEmailCode(ctx, request.UserID, request.Code)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveVerifyEmailCode(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIVerifyEmailCode

	if _code := ctx.Query("code"); _code != "" {
		var code int64
		code, err = strconv.ParseInt(_code, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Code = code
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPIVerifyEmailCode
	if response, err = http.verifyEmailCode(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) sendEmailVerification(ctx context.Context, request requestAuthAPISendEmailVerification) (response responseAuthAPISendEmailVerification, err error) {

	err = http.svc.SendEmailVerification(ctx, request.UserID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveSendEmailVerification(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPISendEmailVerification

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPISendEmailVerification
	if response, err = http.sendEmailVerification(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
