// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"
	"time"

	v2 "github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type metricsAuthAPI struct {
	next externalAPI.AuthAPI
}

func metricsMiddlewareAuthAPI(next externalAPI.AuthAPI) externalAPI.AuthAPI {
	return &metricsAuthAPI{next: next}
}

func (m metricsAuthAPI) LoginUser(ctx context.Context, email string, password string) (userID uuid.UUID, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "loginUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "loginUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "loginUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.LoginUser(ctx, email, password)
}

func (m metricsAuthAPI) SignUpUser(ctx context.Context, email string, password string, name string, surename string) (userID uuid.UUID, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "signUpUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "signUpUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "signUpUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.SignUpUser(ctx, email, password, name, surename)
}

func (m metricsAuthAPI) LogoutUser(ctx context.Context, userID uuid.UUID) (err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "logoutUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "logoutUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "logoutUser", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.LogoutUser(ctx, userID)
}

func (m metricsAuthAPI) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "changePassword", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "changePassword", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "changePassword", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.ChangePassword(ctx, userID, oldPassword, newPassword)
}

func (m metricsAuthAPI) VerifyEmailCode(ctx context.Context, userID uuid.UUID, code int64) (err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "verifyEmailCode", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "verifyEmailCode", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "verifyEmailCode", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.VerifyEmailCode(ctx, userID, code)
}

func (m metricsAuthAPI) SendEmailVerification(ctx context.Context, userID uuid.UUID) (err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("authAPI", "sendEmailVerification", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("authAPI", "sendEmailVerification", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("authAPI", "sendEmailVerification", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.SendEmailVerification(ctx, userID)
}
