// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
	uuid "github.com/google/uuid"
	customhandlers "github.com/mbatimel/AMC/auth/internal/transport/custom-handlers"
)

func (http *httpAuthAPI) loginUser(ctx context.Context, request requestAuthAPILoginUser) (response responseAuthAPILoginUser, err error) {

	response.UserID, err = http.svc.LoginUser(ctx, request.Email, request.Password)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveLoginUser(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPILoginUser
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseAuthAPILoginUser
	if response, err = http.loginUser(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) logoutUser(ctx context.Context, request requestAuthAPILogoutUser) (response responseAuthAPILogoutUser, err error) {

	err = http.svc.LogoutUser(ctx, request.UserID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveLogoutUser(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPILogoutUser

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPILogoutUser
	if response, err = http.logoutUser(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) changePassword(ctx context.Context, request requestAuthAPIChangePassword) (response responseAuthAPIChangePassword, err error) {

	err = http.svc.ChangePassword(ctx, request.UserID, request.OldPassword, request.NewPassword)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveChangePassword(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIChangePassword
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPIChangePassword
	if response, err = http.changePassword(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) verifyEmailCode(ctx context.Context, request requestAuthAPIVerifyEmailCode) (response responseAuthAPIVerifyEmailCode, err error) {

	err = http.svc.VerifyEmailCode(ctx, request.UserID, request.Code)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveVerifyEmailCode(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIVerifyEmailCode

	if _code := ctx.Query("code"); _code != "" {
		var code int64
		code, err = strconv.ParseInt(_code, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "url arguments could not be decoded: "+err.Error())
		}
		request.Code = code
	}

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPIVerifyEmailCode
	if response, err = http.verifyEmailCode(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) sendEmailVerification(ctx context.Context, request requestAuthAPISendEmailVerification) (response responseAuthAPISendEmailVerification, err error) {

	err = http.svc.SendEmailVerification(ctx, request.UserID)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveSendEmailVerification(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPISendEmailVerification

	if _userID := string(ctx.Request().Header.Peek("X-User-Id")); _userID != "" {
		var userID uuid.UUID
		userID, _ = uuid.Parse(_userID)
		request.UserID = userID
	}

	var response responseAuthAPISendEmailVerification
	if response, err = http.sendEmailVerification(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpAuthAPI) requestPasswordReset(ctx context.Context, request requestAuthAPIRequestPasswordReset) (response responseAuthAPIRequestPasswordReset, err error) {

	response.EmailSent, err = http.svc.RequestPasswordReset(ctx, request.Email)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveRequestPasswordReset(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIRequestPasswordReset
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.RequestPasswordReset(ctx, http.svc, request.Email)
}
func (http *httpAuthAPI) confirmPasswordReset(ctx context.Context, request requestAuthAPIConfirmPasswordReset) (response responseAuthAPIConfirmPasswordReset, err error) {

	err = http.svc.ConfirmPasswordReset(ctx, request.Token, request.NewPassword)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuthAPI) serveConfirmPasswordReset(ctx *fiber.Ctx) (err error) {

	var request requestAuthAPIConfirmPasswordReset
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.ConfirmPasswordReset(ctx, http.svc, request.Token, request.NewPassword)
}
