// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type serverAuthAPI struct {
	svc                   externalAPI.AuthAPI
	loginUser             AuthAPILoginUser
	signUpUser            AuthAPISignUpUser
	changePassword        AuthAPIChangePassword
	verifyEmailCode       AuthAPIVerifyEmailCode
	sendEmailVerification AuthAPISendEmailVerification
}

type MiddlewareSetAuthAPI interface {
	Wrap(m MiddlewareAuthAPI)
	WrapLoginUser(m MiddlewareAuthAPILoginUser)
	WrapSignUpUser(m MiddlewareAuthAPISignUpUser)
	WrapChangePassword(m MiddlewareAuthAPIChangePassword)
	WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode)
	WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification)

	WithMetrics()
	WithLog()
}

func newServerAuthAPI(svc externalAPI.AuthAPI) *serverAuthAPI {
	return &serverAuthAPI{
		changePassword:        svc.ChangePassword,
		loginUser:             svc.LoginUser,
		sendEmailVerification: svc.SendEmailVerification,
		signUpUser:            svc.SignUpUser,
		svc:                   svc,
		verifyEmailCode:       svc.VerifyEmailCode,
	}
}

func (srv *serverAuthAPI) Wrap(m MiddlewareAuthAPI) {
	srv.svc = m(srv.svc)
	srv.loginUser = srv.svc.LoginUser
	srv.signUpUser = srv.svc.SignUpUser
	srv.changePassword = srv.svc.ChangePassword
	srv.verifyEmailCode = srv.svc.VerifyEmailCode
	srv.sendEmailVerification = srv.svc.SendEmailVerification
}

func (srv *serverAuthAPI) LoginUser(ctx context.Context, email string, password string) (userID uuid.UUID, err error) {
	return srv.loginUser(ctx, email, password)
}

func (srv *serverAuthAPI) SignUpUser(ctx context.Context, email string, password string, name string, surename string) (userID uuid.UUID, err error) {
	return srv.signUpUser(ctx, email, password, name, surename)
}

func (srv *serverAuthAPI) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error) {
	return srv.changePassword(ctx, userID, oldPassword, newPassword)
}

func (srv *serverAuthAPI) VerifyEmailCode(ctx context.Context, userID uuid.UUID, code int64) (err error) {
	return srv.verifyEmailCode(ctx, userID, code)
}

func (srv *serverAuthAPI) SendEmailVerification(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.sendEmailVerification(ctx, userID)
}

func (srv *serverAuthAPI) WrapLoginUser(m MiddlewareAuthAPILoginUser) {
	srv.loginUser = m(srv.loginUser)
}

func (srv *serverAuthAPI) WrapSignUpUser(m MiddlewareAuthAPISignUpUser) {
	srv.signUpUser = m(srv.signUpUser)
}

func (srv *serverAuthAPI) WrapChangePassword(m MiddlewareAuthAPIChangePassword) {
	srv.changePassword = m(srv.changePassword)
}

func (srv *serverAuthAPI) WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode) {
	srv.verifyEmailCode = m(srv.verifyEmailCode)
}

func (srv *serverAuthAPI) WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification) {
	srv.sendEmailVerification = m(srv.sendEmailVerification)
}

func (srv *serverAuthAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAuthAPI)
}

func (srv *serverAuthAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAuthAPI())
}
