// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type serverAuthAPI struct {
	svc                   externalAPI.AuthAPI
	loginUser             AuthAPILoginUser
	logoutUser            AuthAPILogoutUser
	changePassword        AuthAPIChangePassword
	verifyEmailCode       AuthAPIVerifyEmailCode
	sendEmailVerification AuthAPISendEmailVerification
	requestPasswordReset  AuthAPIRequestPasswordReset
	confirmPasswordReset  AuthAPIConfirmPasswordReset
}

type MiddlewareSetAuthAPI interface {
	Wrap(m MiddlewareAuthAPI)
	WrapLoginUser(m MiddlewareAuthAPILoginUser)
	WrapLogoutUser(m MiddlewareAuthAPILogoutUser)
	WrapChangePassword(m MiddlewareAuthAPIChangePassword)
	WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode)
	WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification)
	WrapRequestPasswordReset(m MiddlewareAuthAPIRequestPasswordReset)
	WrapConfirmPasswordReset(m MiddlewareAuthAPIConfirmPasswordReset)

	WithMetrics()
	WithLog()
}

func newServerAuthAPI(svc externalAPI.AuthAPI) *serverAuthAPI {
	return &serverAuthAPI{
		changePassword:        svc.ChangePassword,
		confirmPasswordReset:  svc.ConfirmPasswordReset,
		loginUser:             svc.LoginUser,
		logoutUser:            svc.LogoutUser,
		requestPasswordReset:  svc.RequestPasswordReset,
		sendEmailVerification: svc.SendEmailVerification,
		svc:                   svc,
		verifyEmailCode:       svc.VerifyEmailCode,
	}
}

func (srv *serverAuthAPI) Wrap(m MiddlewareAuthAPI) {
	srv.svc = m(srv.svc)
	srv.loginUser = srv.svc.LoginUser
	srv.logoutUser = srv.svc.LogoutUser
	srv.changePassword = srv.svc.ChangePassword
	srv.verifyEmailCode = srv.svc.VerifyEmailCode
	srv.sendEmailVerification = srv.svc.SendEmailVerification
	srv.requestPasswordReset = srv.svc.RequestPasswordReset
	srv.confirmPasswordReset = srv.svc.ConfirmPasswordReset
}

func (srv *serverAuthAPI) LoginUser(ctx context.Context, email string, password string) (userID uuid.UUID, err error) {
	return srv.loginUser(ctx, email, password)
}

func (srv *serverAuthAPI) LogoutUser(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.logoutUser(ctx, userID)
}

func (srv *serverAuthAPI) ChangePassword(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error) {
	return srv.changePassword(ctx, userID, oldPassword, newPassword)
}

func (srv *serverAuthAPI) VerifyEmailCode(ctx context.Context, userID uuid.UUID, code int64) (err error) {
	return srv.verifyEmailCode(ctx, userID, code)
}

func (srv *serverAuthAPI) SendEmailVerification(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.sendEmailVerification(ctx, userID)
}

func (srv *serverAuthAPI) RequestPasswordReset(ctx context.Context, email string) (emailSent bool, err error) {
	return srv.requestPasswordReset(ctx, email)
}

func (srv *serverAuthAPI) ConfirmPasswordReset(ctx context.Context, token string, newPassword string) (err error) {
	return srv.confirmPasswordReset(ctx, token, newPassword)
}

func (srv *serverAuthAPI) WrapLoginUser(m MiddlewareAuthAPILoginUser) {
	srv.loginUser = m(srv.loginUser)
}

func (srv *serverAuthAPI) WrapLogoutUser(m MiddlewareAuthAPILogoutUser) {
	srv.logoutUser = m(srv.logoutUser)
}

func (srv *serverAuthAPI) WrapChangePassword(m MiddlewareAuthAPIChangePassword) {
	srv.changePassword = m(srv.changePassword)
}

func (srv *serverAuthAPI) WrapVerifyEmailCode(m MiddlewareAuthAPIVerifyEmailCode) {
	srv.verifyEmailCode = m(srv.verifyEmailCode)
}

func (srv *serverAuthAPI) WrapSendEmailVerification(m MiddlewareAuthAPISendEmailVerification) {
	srv.sendEmailVerification = m(srv.sendEmailVerification)
}

func (srv *serverAuthAPI) WrapRequestPasswordReset(m MiddlewareAuthAPIRequestPasswordReset) {
	srv.requestPasswordReset = m(srv.requestPasswordReset)
}

func (srv *serverAuthAPI) WrapConfirmPasswordReset(m MiddlewareAuthAPIConfirmPasswordReset) {
	srv.confirmPasswordReset = m(srv.confirmPasswordReset)
}

func (srv *serverAuthAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAuthAPI)
}

func (srv *serverAuthAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAuthAPI())
}
