// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/auth/pkg/interfaces/externalAPI"
)

type AuthAPILoginUser func(ctx context.Context, email string, password string) (userID uuid.UUID, err error)
type AuthAPISignUpUser func(ctx context.Context, email string, password string, name string, surename string) (userID uuid.UUID, err error)
type AuthAPILogoutUser func(ctx context.Context, userID uuid.UUID) (err error)
type AuthAPIChangePassword func(ctx context.Context, userID uuid.UUID, oldPassword string, newPassword string) (err error)
type AuthAPIVerifyEmailCode func(ctx context.Context, userID uuid.UUID, code int64) (err error)
type AuthAPISendEmailVerification func(ctx context.Context, userID uuid.UUID) (err error)

type MiddlewareAuthAPI func(next externalAPI.AuthAPI) externalAPI.AuthAPI

type MiddlewareAuthAPILoginUser func(next AuthAPILoginUser) AuthAPILoginUser
type MiddlewareAuthAPISignUpUser func(next AuthAPISignUpUser) AuthAPISignUpUser
type MiddlewareAuthAPILogoutUser func(next AuthAPILogoutUser) AuthAPILogoutUser
type MiddlewareAuthAPIChangePassword func(next AuthAPIChangePassword) AuthAPIChangePassword
type MiddlewareAuthAPIVerifyEmailCode func(next AuthAPIVerifyEmailCode) AuthAPIVerifyEmailCode
type MiddlewareAuthAPISendEmailVerification func(next AuthAPISendEmailVerification) AuthAPISendEmailVerification
