// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/integrations/pkg/interfaces/internalAPI"
)

type OnecOrdersAPIOnecOrderStatusWebhook func(ctx context.Context, apiKey string, clientOrderID uuid.UUID, status string, onecDocumentNumber string, comment string) (ok bool, err error)

type MiddlewareOnecOrdersAPI func(next internalAPI.OnecOrdersAPI) internalAPI.OnecOrdersAPI

type MiddlewareOnecOrdersAPIOnecOrderStatusWebhook func(next OnecOrdersAPIOnecOrderStatusWebhook) OnecOrdersAPIOnecOrderStatusWebhook
