// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/integrations/pkg/interfaces/internalAPI"
)

type serverOnecOrdersAPI struct {
	svc                    internalAPI.OnecOrdersAPI
	onecOrderStatusWebhook OnecOrdersAPIOnecOrderStatusWebhook
}

type MiddlewareSetOnecOrdersAPI interface {
	Wrap(m MiddlewareOnecOrdersAPI)
	WrapOnecOrderStatusWebhook(m MiddlewareOnecOrdersAPIOnecOrderStatusWebhook)

	WithMetrics()
	WithLog()
}

func newServerOnecOrdersAPI(svc internalAPI.OnecOrdersAPI) *serverOnecOrdersAPI {
	return &serverOnecOrdersAPI{
		onecOrderStatusWebhook: svc.OnecOrderStatusWebhook,
		svc:                    svc,
	}
}

func (srv *serverOnecOrdersAPI) Wrap(m MiddlewareOnecOrdersAPI) {
	srv.svc = m(srv.svc)
	srv.onecOrderStatusWebhook = srv.svc.OnecOrderStatusWebhook
}

func (srv *serverOnecOrdersAPI) OnecOrderStatusWebhook(ctx context.Context, apiKey string, clientOrderID uuid.UUID, status string, onecDocumentNumber string, comment string) (ok bool, err error) {
	return srv.onecOrderStatusWebhook(ctx, apiKey, clientOrderID, status, onecDocumentNumber, comment)
}

func (srv *serverOnecOrdersAPI) WrapOnecOrderStatusWebhook(m MiddlewareOnecOrdersAPIOnecOrderStatusWebhook) {
	srv.onecOrderStatusWebhook = m(srv.onecOrderStatusWebhook)
}

func (srv *serverOnecOrdersAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareOnecOrdersAPI)
}

func (srv *serverOnecOrdersAPI) WithLog() {
	srv.Wrap(loggerMiddlewareOnecOrdersAPI())
}
