// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"strconv"
	"time"

	v2 "github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/integrations/pkg/interfaces/internalAPI"
)

type metricsOnecOrdersAPI struct {
	next internalAPI.OnecOrdersAPI
}

func metricsMiddlewareOnecOrdersAPI(next internalAPI.OnecOrdersAPI) internalAPI.OnecOrdersAPI {
	return &metricsOnecOrdersAPI{next: next}
}

func (m metricsOnecOrdersAPI) OnecOrderStatusWebhook(ctx context.Context, apiKey string, clientOrderID uuid.UUID, status string, onecDocumentNumber string, comment string) (ok bool, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("onecOrdersAPI", "onecOrderStatusWebhook", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("onecOrdersAPI", "onecOrderStatusWebhook", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("onecOrdersAPI", "onecOrderStatusWebhook", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.OnecOrderStatusWebhook(ctx, apiKey, clientOrderID, status, onecDocumentNumber, comment)
}
