// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/integrations/pkg/interfaces/internalAPI"
)

type httpOnecOrdersAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverOnecOrdersAPI
	base             internalAPI.OnecOrdersAPI
}

func NewOnecOrdersAPI(svcOnecOrdersAPI internalAPI.OnecOrdersAPI) (srv *httpOnecOrdersAPI) {

	srv = &httpOnecOrdersAPI{
		base: svcOnecOrdersAPI,
		svc:  newServerOnecOrdersAPI(svcOnecOrdersAPI),
	}
	return
}

func (http *httpOnecOrdersAPI) Service() *serverOnecOrdersAPI {
	return http.svc
}

func (http *httpOnecOrdersAPI) WithLog() *httpOnecOrdersAPI {
	http.svc.WithLog()
	return http
}

func (http *httpOnecOrdersAPI) WithMetrics() *httpOnecOrdersAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpOnecOrdersAPI) WithErrorHandler(handler ErrorHandler) *httpOnecOrdersAPI {
	http.errorHandler = handler
	return http
}

func (http *httpOnecOrdersAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/onec/orders/status", http.serveOnecOrderStatusWebhook)
}
