// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package internalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/integrations/internal/transport/jsonRPC/internalapi/viewer"
	"github.com/mbatimel/AMC/integrations/pkg/interfaces/internalAPI"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerOnecOrdersAPI struct {
	next internalAPI.OnecOrdersAPI
}

func loggerMiddlewareOnecOrdersAPI() MiddlewareOnecOrdersAPI {
	return func(next internalAPI.OnecOrdersAPI) internalAPI.OnecOrdersAPI {
		return &loggerOnecOrdersAPI{next: next}
	}
}

func (m loggerOnecOrdersAPI) OnecOrderStatusWebhook(ctx context.Context, apiKey string, clientOrderID uuid.UUID, status string, onecDocumentNumber string, comment string) (ok bool, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OnecOrdersAPI").Str("method", "onecOrderStatusWebhook").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "onecOrdersAPI.onecOrderStatusWebhook",
				"request": viewer.Sprintf("%+v", requestOnecOrdersAPIOnecOrderStatusWebhook{
					ApiKey:             apiKey,
					ClientOrderID:      clientOrderID,
					Comment:            comment,
					OnecDocumentNumber: onecDocumentNumber,
					Status:             status,
				}),
				"response": viewer.Sprintf("%+v", responseOnecOrdersAPIOnecOrderStatusWebhook{Ok: ok}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call onecOrderStatusWebhook")
			return
		}
		logger.Info().Func(logHandle).Msg("call onecOrderStatusWebhook")
	}(time.Now())
	return m.next.OnecOrderStatusWebhook(ctx, apiKey, clientOrderID, status, onecDocumentNumber, comment)
}
