// Package transport is a hand-written HTTP client for auth's LoginUser,
// used for server-to-server calls (back/admin calls this to authenticate
// staff without duplicating password storage/verification).
//
// This is NOT generated by `tg client` — that generator miscompiles
// AuthAPI because two of its other methods (RegisterIP, RegisterIndividual)
// take optional (*string) parameters, which `tg` v2.3.95's client mode
// cannot type-check correctly. Only LoginUser is implemented here; add
// more methods by hand, in this same style, if a future service needs them.
package transport

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/access/pkg/client/transport/httpclient"
	fasthttp "github.com/valyala/fasthttp"
)

type ClientAuthAPI struct {
	httpClient *httpclient.ClientHTTP
}

// LoginError is returned by LoginUser when auth's /api/v1/auth/login
// responds with a non-200 status. It carries the real HTTP status code
// so callers (e.g. back/admin) can tell "wrong password" (401) apart from
// "auth is down" (5xx) instead of collapsing every failure into the same
// generic error.
type LoginError struct {
	StatusCode int
}

func (e *LoginError) Error() string {
	return fmt.Sprintf("auth login failed: HTTP %d", e.StatusCode)
}

func NewClientAuthAPI(endpoint string, opts ...httpclient.Option) (client *ClientAuthAPI) {
	httpClient := httpclient.NewClient(endpoint, opts...)
	return &ClientAuthAPI{httpClient: httpClient}
}

// loginUserResponse mirrors the generated responseAuthAPILoginUser wire
// shape (back/auth/internal/transport/jsonRPC/externalapi/authapi-exchange.go):
// LoginUser has no @tg http-response annotation, so its generated handler
// encodes this struct directly on success — no envelope, no wrapping.
type loginUserResponse struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// LoginUser performs the LoginUser operation (POST /api/v1/auth/login).
// Credentials use the same JSON contract as the public frontend.
func (cli *ClientAuthAPI) LoginUser(ctx context.Context, email string, password string) (userID uuid.UUID, err error) {

	reqBody, err := json.Marshal(struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}{
		Email:    email,
		Password: password,
	})
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/auth/login", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	if _resp.StatusCode() != fasthttp.StatusOK {
		err = &LoginError{StatusCode: _resp.StatusCode()}
		return
	}
	var response loginUserResponse
	if err = json.Unmarshal(_resp.Body(), &response); err != nil {
		return
	}
	userID = response.UserID
	return
}
