// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/products/pkg/client/transport/httpclient"
	fasthttp "github.com/valyala/fasthttp"
)

type ClientProductsInternalAPI struct {
	httpClient *httpclient.ClientHTTP
}

func NewClientProductsInternalAPI(endpoint string, opts ...httpclient.Option) (client *ClientProductsInternalAPI) {
	httpClient := httpclient.NewClient(endpoint, opts...)
	return &ClientProductsInternalAPI{httpClient: httpClient}
}

// SetMarketplaceStatus performs the SetMarketplaceStatus operation.
func (cli *ClientProductsInternalAPI) SetMarketplaceStatus(ctx context.Context, productID uuid.UUID, marketplace string, status string) (ok bool, err error) {

	var reqBody []byte
	_request := requestProductsInternalAPISetMarketplaceStatus{}
	reqBody, err = json.Marshal(_request)
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/products/marketplace-status", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_req.URI().QueryArgs().Set("productID", fmt.Sprint(productID))
	_req.URI().QueryArgs().Set("marketplace", marketplace)
	_req.URI().QueryArgs().Set("status", status)
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	respBody := _resp.Body()
	if _resp.StatusCode() != 200 {
		err = fmt.Errorf("HTTP error: %d. URL: %s, Method: %s, Body: %s", _resp.StatusCode(), _req.URI().String(), _req.Header.Method(), string(respBody))
		return
	}
	var _response responseProductsInternalAPISetMarketplaceStatus
	if err = json.Unmarshal(respBody, &_response); err != nil {
		return
	}
	ok = _response.Ok
	return
}
