// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/pkg/models"
)

type requestAdminAPILogin struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAdminAPILogin struct {
	Response models.LoginResponse `json:"response,omitempty"`
}

type requestAdminAPILogout struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAdminAPILogout struct{}

type requestAdminAPIGetSession struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type responseAdminAPIGetSession struct {
	Response models.SessionResponse `json:"response,omitempty"`
}

type requestAdminAPIListAuditLog struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Limit  int       `json:"limit,omitempty"`
	Offset int       `json:"offset,omitempty"`
}

type responseAdminAPIListAuditLog struct {
	Response models.ListAuditLogResponse `json:"response,omitempty"`
}

type requestAdminAPICreateSignupRequest struct {
	Company     string `json:"company,omitempty"`
	Inn         string `json:"inn,omitempty"`
	Contact     string `json:"contact,omitempty"`
	Email       string `json:"email,omitempty"`
	Phone       string `json:"phone,omitempty"`
	RequestType string `json:"requestType,omitempty"`
}

type responseAdminAPICreateSignupRequest struct {
	Response models.SignupRequest `json:"response,omitempty"`
}

type requestAdminAPIListSignupRequests struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Status string    `json:"status,omitempty"`
}

type responseAdminAPIListSignupRequests struct {
	Response models.ListSignupRequestsResponse `json:"response,omitempty"`
}

type requestAdminAPIApproveSignupRequest struct {
	UserID    uuid.UUID `json:"userID,omitempty"`
	RequestID uuid.UUID `json:"requestID,omitempty"`
}

type responseAdminAPIApproveSignupRequest struct {
	Response models.SignupRequest `json:"response,omitempty"`
}

type requestAdminAPIRejectSignupRequest struct {
	UserID    uuid.UUID `json:"userID,omitempty"`
	RequestID uuid.UUID `json:"requestID,omitempty"`
	Reason    string    `json:"reason,omitempty"`
}

type responseAdminAPIRejectSignupRequest struct {
	Response models.SignupRequest `json:"response,omitempty"`
}

type requestAdminAPIListLegalDocs struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type responseAdminAPIListLegalDocs struct {
	Response models.ListLegalDocsResponse `json:"response,omitempty"`
}

// Formal exchange type, please do not delete.
type requestAdminAPIListPublicLegalDocs struct{}

type responseAdminAPIListPublicLegalDocs struct {
	Response models.ListLegalDocsResponse `json:"response,omitempty"`
}

type requestAdminAPICreateLegalDoc struct {
	UserID            uuid.UUID `json:"userID,omitempty"`
	Id                string    `json:"id,omitempty"`
	Name              string    `json:"name,omitempty"`
	Version           string    `json:"version,omitempty"`
	Summary           string    `json:"summary,omitempty"`
	FileName          string    `json:"fileName,omitempty"`
	FileContentBase64 string    `json:"fileContentBase64,omitempty"`
}

type responseAdminAPICreateLegalDoc struct {
	Response models.LegalDoc `json:"response,omitempty"`
}

type requestAdminAPIReplaceLegalDocFile struct {
	UserID            uuid.UUID `json:"userID,omitempty"`
	DocID             string    `json:"docID,omitempty"`
	Version           string    `json:"version,omitempty"`
	Summary           string    `json:"summary,omitempty"`
	FileName          string    `json:"fileName,omitempty"`
	FileContentBase64 string    `json:"fileContentBase64,omitempty"`
}

type responseAdminAPIReplaceLegalDocFile struct {
	Response models.LegalDoc `json:"response,omitempty"`
}

type requestAdminAPIDeleteLegalDoc struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	DocID  string    `json:"docID,omitempty"`
}

type responseAdminAPIDeleteLegalDoc struct {
	Response models.DeleteLegalDocResponse `json:"response,omitempty"`
}

type requestAdminAPIListLegalDocVersions struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	DocID  string    `json:"docID,omitempty"`
}

type responseAdminAPIListLegalDocVersions struct {
	Response models.ListLegalDocVersionsResponse `json:"response,omitempty"`
}

type requestAdminAPIListCertificates struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type responseAdminAPIListCertificates struct {
	Response models.ListCertificatesResponse `json:"response,omitempty"`
}

// Formal exchange type, please do not delete.
type requestAdminAPIListPublicCertificates struct{}

type responseAdminAPIListPublicCertificates struct {
	Response models.ListCertificatesResponse `json:"response,omitempty"`
}

type requestAdminAPICreateCertificate struct {
	UserID            uuid.UUID `json:"userID,omitempty"`
	Title             string    `json:"title,omitempty"`
	SortOrder         int       `json:"sortOrder,omitempty"`
	IsActive          bool      `json:"isActive,omitempty"`
	FileName          string    `json:"fileName,omitempty"`
	FileContentBase64 string    `json:"fileContentBase64,omitempty"`
}

type responseAdminAPICreateCertificate struct {
	Response models.Certificate `json:"response,omitempty"`
}

type requestAdminAPIUpdateCertificate struct {
	UserID            uuid.UUID `json:"userID,omitempty"`
	CertID            uuid.UUID `json:"certID,omitempty"`
	Title             string    `json:"title,omitempty"`
	SortOrder         int       `json:"sortOrder,omitempty"`
	IsActive          bool      `json:"isActive,omitempty"`
	FileName          string    `json:"fileName,omitempty"`
	FileContentBase64 string    `json:"fileContentBase64,omitempty"`
}

type responseAdminAPIUpdateCertificate struct {
	Response models.Certificate `json:"response,omitempty"`
}

type requestAdminAPIDeleteCertificate struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	CertID uuid.UUID `json:"certID,omitempty"`
}

type responseAdminAPIDeleteCertificate struct {
	Response models.DeleteCertificateResponse `json:"response,omitempty"`
}
