// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/admin/pkg/models"
)

type serverAdminAPI struct {
	svc                  externalapi.AdminAPI
	login                AdminAPILogin
	logout               AdminAPILogout
	getSession           AdminAPIGetSession
	listAuditLog         AdminAPIListAuditLog
	createSignupRequest  AdminAPICreateSignupRequest
	listSignupRequests   AdminAPIListSignupRequests
	approveSignupRequest AdminAPIApproveSignupRequest
	rejectSignupRequest  AdminAPIRejectSignupRequest
}

type MiddlewareSetAdminAPI interface {
	Wrap(m MiddlewareAdminAPI)
	WrapLogin(m MiddlewareAdminAPILogin)
	WrapLogout(m MiddlewareAdminAPILogout)
	WrapGetSession(m MiddlewareAdminAPIGetSession)
	WrapListAuditLog(m MiddlewareAdminAPIListAuditLog)
	WrapCreateSignupRequest(m MiddlewareAdminAPICreateSignupRequest)
	WrapListSignupRequests(m MiddlewareAdminAPIListSignupRequests)
	WrapApproveSignupRequest(m MiddlewareAdminAPIApproveSignupRequest)
	WrapRejectSignupRequest(m MiddlewareAdminAPIRejectSignupRequest)

	WithMetrics()
	WithLog()
}

func newServerAdminAPI(svc externalapi.AdminAPI) *serverAdminAPI {
	return &serverAdminAPI{
		approveSignupRequest: svc.ApproveSignupRequest,
		createSignupRequest:  svc.CreateSignupRequest,
		getSession:           svc.GetSession,
		listAuditLog:         svc.ListAuditLog,
		listSignupRequests:   svc.ListSignupRequests,
		login:                svc.Login,
		logout:               svc.Logout,
		rejectSignupRequest:  svc.RejectSignupRequest,
		svc:                  svc,
	}
}

func (srv *serverAdminAPI) Wrap(m MiddlewareAdminAPI) {
	srv.svc = m(srv.svc)
	srv.login = srv.svc.Login
	srv.logout = srv.svc.Logout
	srv.getSession = srv.svc.GetSession
	srv.listAuditLog = srv.svc.ListAuditLog
	srv.createSignupRequest = srv.svc.CreateSignupRequest
	srv.listSignupRequests = srv.svc.ListSignupRequests
	srv.approveSignupRequest = srv.svc.ApproveSignupRequest
	srv.rejectSignupRequest = srv.svc.RejectSignupRequest
}

func (srv *serverAdminAPI) Login(ctx context.Context, email string, password string) (response models.LoginResponse, err error) {
	return srv.login(ctx, email, password)
}

func (srv *serverAdminAPI) Logout(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.logout(ctx, userID)
}

func (srv *serverAdminAPI) GetSession(ctx context.Context, userID uuid.UUID) (response models.SessionResponse, err error) {
	return srv.getSession(ctx, userID)
}

func (srv *serverAdminAPI) ListAuditLog(ctx context.Context, userID uuid.UUID, limit int, offset int) (response models.ListAuditLogResponse, err error) {
	return srv.listAuditLog(ctx, userID, limit, offset)
}

func (srv *serverAdminAPI) CreateSignupRequest(ctx context.Context, company string, inn string, contact string, email string, phone string, requestType string) (response models.SignupRequest, err error) {
	return srv.createSignupRequest(ctx, company, inn, contact, email, phone, requestType)
}

func (srv *serverAdminAPI) ListSignupRequests(ctx context.Context, userID uuid.UUID, status string) (response models.ListSignupRequestsResponse, err error) {
	return srv.listSignupRequests(ctx, userID, status)
}

func (srv *serverAdminAPI) ApproveSignupRequest(ctx context.Context, userID uuid.UUID, requestID uuid.UUID) (response models.SignupRequest, err error) {
	return srv.approveSignupRequest(ctx, userID, requestID)
}

func (srv *serverAdminAPI) RejectSignupRequest(ctx context.Context, userID uuid.UUID, requestID uuid.UUID, reason string) (response models.SignupRequest, err error) {
	return srv.rejectSignupRequest(ctx, userID, requestID, reason)
}

func (srv *serverAdminAPI) WrapLogin(m MiddlewareAdminAPILogin) {
	srv.login = m(srv.login)
}

func (srv *serverAdminAPI) WrapLogout(m MiddlewareAdminAPILogout) {
	srv.logout = m(srv.logout)
}

func (srv *serverAdminAPI) WrapGetSession(m MiddlewareAdminAPIGetSession) {
	srv.getSession = m(srv.getSession)
}

func (srv *serverAdminAPI) WrapListAuditLog(m MiddlewareAdminAPIListAuditLog) {
	srv.listAuditLog = m(srv.listAuditLog)
}

func (srv *serverAdminAPI) WrapCreateSignupRequest(m MiddlewareAdminAPICreateSignupRequest) {
	srv.createSignupRequest = m(srv.createSignupRequest)
}

func (srv *serverAdminAPI) WrapListSignupRequests(m MiddlewareAdminAPIListSignupRequests) {
	srv.listSignupRequests = m(srv.listSignupRequests)
}

func (srv *serverAdminAPI) WrapApproveSignupRequest(m MiddlewareAdminAPIApproveSignupRequest) {
	srv.approveSignupRequest = m(srv.approveSignupRequest)
}

func (srv *serverAdminAPI) WrapRejectSignupRequest(m MiddlewareAdminAPIRejectSignupRequest) {
	srv.rejectSignupRequest = m(srv.rejectSignupRequest)
}

func (srv *serverAdminAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAdminAPI)
}

func (srv *serverAdminAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAdminAPI())
}
