// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/admin/pkg/models"
)

type AdminAPILogin func(ctx context.Context, email string, password string) (response models.LoginResponse, err error)
type AdminAPILogout func(ctx context.Context, userID uuid.UUID) (err error)
type AdminAPIGetSession func(ctx context.Context, userID uuid.UUID) (response models.SessionResponse, err error)
type AdminAPIListAuditLog func(ctx context.Context, userID uuid.UUID, limit int, offset int) (response models.ListAuditLogResponse, err error)

type MiddlewareAdminAPI func(next externalapi.AdminAPI) externalapi.AdminAPI

type MiddlewareAdminAPILogin func(next AdminAPILogin) AdminAPILogin
type MiddlewareAdminAPILogout func(next AdminAPILogout) AdminAPILogout
type MiddlewareAdminAPIGetSession func(next AdminAPIGetSession) AdminAPIGetSession
type MiddlewareAdminAPIListAuditLog func(next AdminAPIListAuditLog) AdminAPIListAuditLog
