// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/pkg/models"
)

type requestAdminAPILogin struct {
	Email    string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAdminAPILogin struct {
	Response models.LoginResponse `json:"response,omitempty"`
}

type requestAdminAPILogout struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

// Formal exchange type, please do not delete.
type responseAdminAPILogout struct{}

type requestAdminAPIGetSession struct {
	UserID uuid.UUID `json:"userID,omitempty"`
}

type responseAdminAPIGetSession struct {
	Response models.SessionResponse `json:"response,omitempty"`
}

type requestAdminAPIListAuditLog struct {
	UserID uuid.UUID `json:"userID,omitempty"`
	Limit  int       `json:"limit,omitempty"`
	Offset int       `json:"offset,omitempty"`
}

type responseAdminAPIListAuditLog struct {
	Response models.ListAuditLogResponse `json:"response,omitempty"`
}
