// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/AMC/admin/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/admin/pkg/models"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerAdminAPI struct {
	next externalapi.AdminAPI
}

func loggerMiddlewareAdminAPI() MiddlewareAdminAPI {
	return func(next externalapi.AdminAPI) externalapi.AdminAPI {
		return &loggerAdminAPI{next: next}
	}
}

func (m loggerAdminAPI) Login(ctx context.Context, email string, password string) (response models.LoginResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AdminAPI").Str("method", "login").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "adminAPI.login",
				"request": viewer.Sprintf("%+v", requestAdminAPILogin{
					Email:    email,
					Password: password,
				}),
				"response": viewer.Sprintf("%+v", responseAdminAPILogin{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call login")
			return
		}
		logger.Info().Func(logHandle).Msg("call login")
	}(time.Now())
	return m.next.Login(ctx, email, password)
}

func (m loggerAdminAPI) Logout(ctx context.Context, userID uuid.UUID) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "AdminAPI").Str("method", "logout").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "adminAPI.logout",
				"request":  viewer.Sprintf("%+v", requestAdminAPILogout{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseAdminAPILogout{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call logout")
			return
		}
		logger.Info().Func(logHandle).Msg("call logout")
	}(time.Now())
	return m.next.Logout(ctx, userID)
}

func (m loggerAdminAPI) GetSession(ctx context.Context, userID uuid.UUID) (response models.SessionResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AdminAPI").Str("method", "getSession").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "adminAPI.getSession",
				"request":  viewer.Sprintf("%+v", requestAdminAPIGetSession{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseAdminAPIGetSession{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getSession")
			return
		}
		logger.Info().Func(logHandle).Msg("call getSession")
	}(time.Now())
	return m.next.GetSession(ctx, userID)
}

func (m loggerAdminAPI) ListAuditLog(ctx context.Context, userID uuid.UUID, limit int, offset int) (response models.ListAuditLogResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "AdminAPI").Str("method", "listAuditLog").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "adminAPI.listAuditLog",
				"request": viewer.Sprintf("%+v", requestAdminAPIListAuditLog{
					Limit:  limit,
					Offset: offset,
					UserID: userID,
				}),
				"response": viewer.Sprintf("%+v", responseAdminAPIListAuditLog{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listAuditLog")
			return
		}
		logger.Info().Func(logHandle).Msg("call listAuditLog")
	}(time.Now())
	return m.next.ListAuditLog(ctx, userID, limit, offset)
}
