// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/admin/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/admin/pkg/models"
)

type serverAdminAPI struct {
	svc          externalapi.AdminAPI
	login        AdminAPILogin
	logout       AdminAPILogout
	getSession   AdminAPIGetSession
	listAuditLog AdminAPIListAuditLog
}

type MiddlewareSetAdminAPI interface {
	Wrap(m MiddlewareAdminAPI)
	WrapLogin(m MiddlewareAdminAPILogin)
	WrapLogout(m MiddlewareAdminAPILogout)
	WrapGetSession(m MiddlewareAdminAPIGetSession)
	WrapListAuditLog(m MiddlewareAdminAPIListAuditLog)

	WithMetrics()
	WithLog()
}

func newServerAdminAPI(svc externalapi.AdminAPI) *serverAdminAPI {
	return &serverAdminAPI{
		getSession:   svc.GetSession,
		listAuditLog: svc.ListAuditLog,
		login:        svc.Login,
		logout:       svc.Logout,
		svc:          svc,
	}
}

func (srv *serverAdminAPI) Wrap(m MiddlewareAdminAPI) {
	srv.svc = m(srv.svc)
	srv.login = srv.svc.Login
	srv.logout = srv.svc.Logout
	srv.getSession = srv.svc.GetSession
	srv.listAuditLog = srv.svc.ListAuditLog
}

func (srv *serverAdminAPI) Login(ctx context.Context, email string, password string) (response models.LoginResponse, err error) {
	return srv.login(ctx, email, password)
}

func (srv *serverAdminAPI) Logout(ctx context.Context, userID uuid.UUID) (err error) {
	return srv.logout(ctx, userID)
}

func (srv *serverAdminAPI) GetSession(ctx context.Context, userID uuid.UUID) (response models.SessionResponse, err error) {
	return srv.getSession(ctx, userID)
}

func (srv *serverAdminAPI) ListAuditLog(ctx context.Context, userID uuid.UUID, limit int, offset int) (response models.ListAuditLogResponse, err error) {
	return srv.listAuditLog(ctx, userID, limit, offset)
}

func (srv *serverAdminAPI) WrapLogin(m MiddlewareAdminAPILogin) {
	srv.login = m(srv.login)
}

func (srv *serverAdminAPI) WrapLogout(m MiddlewareAdminAPILogout) {
	srv.logout = m(srv.logout)
}

func (srv *serverAdminAPI) WrapGetSession(m MiddlewareAdminAPIGetSession) {
	srv.getSession = m(srv.getSession)
}

func (srv *serverAdminAPI) WrapListAuditLog(m MiddlewareAdminAPIListAuditLog) {
	srv.listAuditLog = m(srv.listAuditLog)
}

func (srv *serverAdminAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareAdminAPI)
}

func (srv *serverAdminAPI) WithLog() {
	srv.Wrap(loggerMiddlewareAdminAPI())
}
