// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/access/pkg/client/transport/httpclient"
	fasthttp "github.com/valyala/fasthttp"
)

type ClientAccessAPI struct {
	httpClient *httpclient.ClientHTTP
}

func NewClientAccessAPI(endpoint string, opts ...httpclient.Option) (client *ClientAccessAPI) {
	httpClient := httpclient.NewClient(endpoint, opts...)
	return &ClientAccessAPI{httpClient: httpClient}
}

// CheckAccess performs the CheckAccess operation.
func (cli *ClientAccessAPI) CheckAccess(ctx context.Context, userID uuid.UUID, role int) (allowed bool, err error) {

	var reqBody []byte
	_request := requestAccessAPICheckAccess{}
	reqBody, err = json.Marshal(_request)
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/access/check", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_req.URI().QueryArgs().Set("userID", fmt.Sprint(userID))
	_req.URI().QueryArgs().Set("role", fmt.Sprint(role))
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	respBody := _resp.Body()
	if _resp.StatusCode() != 200 {
		err = fmt.Errorf("HTTP error: %d. URL: %s, Method: %s, Body: %s", _resp.StatusCode(), _req.URI().String(), _req.Header.Method(), string(respBody))
		return
	}
	var _response responseAccessAPICheckAccess
	if err = json.Unmarshal(respBody, &_response); err != nil {
		return
	}
	allowed = _response.Allowed
	return
}

// AddRole performs the AddRole operation.
func (cli *ClientAccessAPI) AddRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {

	var reqBody []byte
	_request := requestAccessAPIAddRole{}
	reqBody, err = json.Marshal(_request)
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/access/role/add", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_req.Header.Set("X-Admin-User-Id", fmt.Sprint(adminUserID))
	_req.URI().QueryArgs().Set("role", fmt.Sprint(role))
	_req.URI().QueryArgs().Set("userID", fmt.Sprint(userID))
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	respBody := _resp.Body()
	if _resp.StatusCode() != 200 {
		err = fmt.Errorf("HTTP error: %d. URL: %s, Method: %s, Body: %s", _resp.StatusCode(), _req.URI().String(), _req.Header.Method(), string(respBody))
		return
	}
	var _response responseAccessAPIAddRole
	if err = json.Unmarshal(respBody, &_response); err != nil {
		return
	}
	success = _response.Success
	return
}

// UpdateRole performs the UpdateRole operation.
func (cli *ClientAccessAPI) UpdateRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {

	var reqBody []byte
	_request := requestAccessAPIUpdateRole{}
	reqBody, err = json.Marshal(_request)
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/access/role/update", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_req.Header.Set("X-Admin-User-Id", fmt.Sprint(adminUserID))
	_req.URI().QueryArgs().Set("userID", fmt.Sprint(userID))
	_req.URI().QueryArgs().Set("role", fmt.Sprint(role))
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	respBody := _resp.Body()
	if _resp.StatusCode() != 200 {
		err = fmt.Errorf("HTTP error: %d. URL: %s, Method: %s, Body: %s", _resp.StatusCode(), _req.URI().String(), _req.Header.Method(), string(respBody))
		return
	}
	var _response responseAccessAPIUpdateRole
	if err = json.Unmarshal(respBody, &_response); err != nil {
		return
	}
	success = _response.Success
	return
}

// DeleteRole performs the DeleteRole operation.
func (cli *ClientAccessAPI) DeleteRole(ctx context.Context, adminUserID uuid.UUID, userID uuid.UUID, role int) (success bool, err error) {

	var reqBody []byte
	_request := requestAccessAPIDeleteRole{}
	reqBody, err = json.Marshal(_request)
	if err != nil {
		return
	}
	_req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(_req)
	_req.SetRequestURI(fmt.Sprintf("%s/api/v1/access/role/delete", cli.httpClient.BaseURL))
	_req.Header.SetMethod("POST")
	_req.Header.Set("Content-Type", "application/json")
	_req.SetBody(reqBody)
	_req.Header.Set("X-Admin-User-Id", fmt.Sprint(adminUserID))
	_req.URI().QueryArgs().Set("userID", fmt.Sprint(userID))
	_req.URI().QueryArgs().Set("role", fmt.Sprint(role))
	_resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(_resp)
	if deadline, ok := ctx.Deadline(); ok {
		timeout := time.Until(deadline)
		cli.httpClient.SetTimeout(timeout)
	}
	if err = cli.httpClient.Do(ctx, _req, _resp); err != nil {
		return
	}
	respBody := _resp.Body()
	if _resp.StatusCode() != 200 {
		err = fmt.Errorf("HTTP error: %d. URL: %s, Method: %s, Body: %s", _resp.StatusCode(), _req.URI().String(), _req.Header.Method(), string(respBody))
		return
	}
	var _response responseAccessAPIDeleteRole
	if err = json.Unmarshal(respBody, &_response); err != nil {
		return
	}
	success = _response.Success
	return
}
