// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/orders/pkg/interfaces/externalAPI"
	"github.com/mbatimel/AMC/orders/pkg/models"
)

type OrdersAPIGetCart func(ctx context.Context, userID uuid.UUID, clientID string) (models.GetCartResponse, error)

type MiddlewareOrdersAPI func(next externalAPI.OrdersAPI) externalAPI.OrdersAPI

type MiddlewareOrdersAPIGetCart func(next OrdersAPIGetCart) OrdersAPIGetCart
