// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/orders/pkg/interfaces/externalAPI"
	"github.com/mbatimel/AMC/orders/pkg/models"
)

type serverOrdersAPI struct {
	svc     externalAPI.OrdersAPI
	getCart OrdersAPIGetCart
}

type MiddlewareSetOrdersAPI interface {
	Wrap(m MiddlewareOrdersAPI)
	WrapGetCart(m MiddlewareOrdersAPIGetCart)

	WithMetrics()
	WithLog()
}

func newServerOrdersAPI(svc externalAPI.OrdersAPI) *serverOrdersAPI {
	return &serverOrdersAPI{
		getCart: svc.GetCart,
		svc:     svc,
	}
}

func (srv *serverOrdersAPI) Wrap(m MiddlewareOrdersAPI) {
	srv.svc = m(srv.svc)
	srv.getCart = srv.svc.GetCart
}

func (srv *serverOrdersAPI) GetCart(ctx context.Context, userID uuid.UUID, clientID string) (models.GetCartResponse, error) {
	return srv.getCart(ctx, userID, clientID)
}

func (srv *serverOrdersAPI) WrapGetCart(m MiddlewareOrdersAPIGetCart) {
	srv.getCart = m(srv.getCart)
}

func (srv *serverOrdersAPI) WithMetrics() {
	srv.Wrap(metricsMiddlewareOrdersAPI)
}

func (srv *serverOrdersAPI) WithLog() {
	srv.Wrap(loggerMiddlewareOrdersAPI())
}
