// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/orders/pkg/models"
)

type requestOrdersAPIGetCart struct {
	UserID   uuid.UUID `json:"userID,omitempty"`
	ClientID string    `json:"clientID,omitempty"`
}

type responseOrdersAPIGetCart struct {
	models.GetCartResponse `json:",omitempty"`
}
