// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/orders/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/AMC/orders/pkg/interfaces/externalapi"
	"github.com/mbatimel/AMC/orders/pkg/models"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerOrdersAPI struct {
	next externalapi.OrdersAPI
}

func loggerMiddlewareOrdersAPI() MiddlewareOrdersAPI {
	return func(next externalapi.OrdersAPI) externalapi.OrdersAPI {
		return &loggerOrdersAPI{next: next}
	}
}

func (m loggerOrdersAPI) GetCart(ctx context.Context, userID uuid.UUID, clientID string) (response models.GetCartResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "getCart").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.getCart",
				"request": viewer.Sprintf("%+v", requestOrdersAPIGetCart{
					ClientID: clientID,
					UserID:   userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIGetCart{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getCart")
			return
		}
		logger.Info().Func(logHandle).Msg("call getCart")
	}(time.Now())
	return m.next.GetCart(ctx, userID, clientID)
}

func (m loggerOrdersAPI) AddCartItem(ctx context.Context, userID uuid.UUID, clientID string, productID string, qty int) (response models.AddCartItemResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "addCartItem").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.addCartItem",
				"request": viewer.Sprintf("%+v", requestOrdersAPIAddCartItem{
					ClientID:  clientID,
					ProductID: productID,
					Qty:       qty,
					UserID:    userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIAddCartItem{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call addCartItem")
			return
		}
		logger.Info().Func(logHandle).Msg("call addCartItem")
	}(time.Now())
	return m.next.AddCartItem(ctx, userID, clientID, productID, qty)
}

func (m loggerOrdersAPI) UpdateCartItem(ctx context.Context, userID uuid.UUID, clientID string, cartItemID string, qty int) (response models.UpdateCartItemResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "updateCartItem").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.updateCartItem",
				"request": viewer.Sprintf("%+v", requestOrdersAPIUpdateCartItem{
					CartItemID: cartItemID,
					ClientID:   clientID,
					Qty:        qty,
					UserID:     userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIUpdateCartItem{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateCartItem")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateCartItem")
	}(time.Now())
	return m.next.UpdateCartItem(ctx, userID, clientID, cartItemID, qty)
}

func (m loggerOrdersAPI) DeleteCartItem(ctx context.Context, userID uuid.UUID, clientID string, cartItemID string) (response models.DeleteCartItemResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "deleteCartItem").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.deleteCartItem",
				"request": viewer.Sprintf("%+v", requestOrdersAPIDeleteCartItem{
					CartItemID: cartItemID,
					ClientID:   clientID,
					UserID:     userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIDeleteCartItem{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteCartItem")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteCartItem")
	}(time.Now())
	return m.next.DeleteCartItem(ctx, userID, clientID, cartItemID)
}

func (m loggerOrdersAPI) ClearCart(ctx context.Context, userID uuid.UUID, clientID string) (response models.ClearCartResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "clearCart").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.clearCart",
				"request": viewer.Sprintf("%+v", requestOrdersAPIClearCart{
					ClientID: clientID,
					UserID:   userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIClearCart{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call clearCart")
			return
		}
		logger.Info().Func(logHandle).Msg("call clearCart")
	}(time.Now())
	return m.next.ClearCart(ctx, userID, clientID)
}

func (m loggerOrdersAPI) CreateOrder(ctx context.Context, userID uuid.UUID, clientID string, deliveryType string, deliveryAddress string, contactName string, phone string, email string, comment string) (response models.CreateOrderResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "createOrder").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.createOrder",
				"request": viewer.Sprintf("%+v", requestOrdersAPICreateOrder{
					ClientID:        clientID,
					Comment:         comment,
					ContactName:     contactName,
					DeliveryAddress: deliveryAddress,
					DeliveryType:    deliveryType,
					Email:           email,
					Phone:           phone,
					UserID:          userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPICreateOrder{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createOrder")
			return
		}
		logger.Info().Func(logHandle).Msg("call createOrder")
	}(time.Now())
	return m.next.CreateOrder(ctx, userID, clientID, deliveryType, deliveryAddress, contactName, phone, email, comment)
}

func (m loggerOrdersAPI) GetOrder(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, clientID string) (response models.GetOrderResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "getOrder").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.getOrder",
				"request": viewer.Sprintf("%+v", requestOrdersAPIGetOrder{
					ClientID: clientID,
					OrderID:  orderID,
					UserID:   userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIGetOrder{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getOrder")
			return
		}
		logger.Info().Func(logHandle).Msg("call getOrder")
	}(time.Now())
	return m.next.GetOrder(ctx, orderID, userID, clientID)
}

func (m loggerOrdersAPI) ListOrders(ctx context.Context, userID uuid.UUID, clientID string, status string, paymentStatus string, limit int, offset int, sort string) (response models.ListOrdersResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "listOrders").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.listOrders",
				"request": viewer.Sprintf("%+v", requestOrdersAPIListOrders{
					ClientID:      clientID,
					Limit:         limit,
					Offset:        offset,
					PaymentStatus: paymentStatus,
					Sort:          sort,
					Status:        status,
					UserID:        userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIListOrders{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listOrders")
			return
		}
		logger.Info().Func(logHandle).Msg("call listOrders")
	}(time.Now())
	return m.next.ListOrders(ctx, userID, clientID, status, paymentStatus, limit, offset, sort)
}

func (m loggerOrdersAPI) CancelOrder(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, comment string) (response models.CancelOrderResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "cancelOrder").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.cancelOrder",
				"request": viewer.Sprintf("%+v", requestOrdersAPICancelOrder{
					Comment: comment,
					OrderID: orderID,
					UserID:  userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPICancelOrder{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call cancelOrder")
			return
		}
		logger.Info().Func(logHandle).Msg("call cancelOrder")
	}(time.Now())
	return m.next.CancelOrder(ctx, orderID, userID, comment)
}

func (m loggerOrdersAPI) RepeatOrder(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, clientID string) (response models.RepeatOrderResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "repeatOrder").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.repeatOrder",
				"request": viewer.Sprintf("%+v", requestOrdersAPIRepeatOrder{
					ClientID: clientID,
					OrderID:  orderID,
					UserID:   userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIRepeatOrder{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call repeatOrder")
			return
		}
		logger.Info().Func(logHandle).Msg("call repeatOrder")
	}(time.Now())
	return m.next.RepeatOrder(ctx, orderID, userID, clientID)
}

func (m loggerOrdersAPI) GetOrderDocuments(ctx context.Context, orderID uuid.UUID, userID uuid.UUID) (response models.GetOrderDocumentsResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "getOrderDocuments").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.getOrderDocuments",
				"request": viewer.Sprintf("%+v", requestOrdersAPIGetOrderDocuments{
					OrderID: orderID,
					UserID:  userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIGetOrderDocuments{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getOrderDocuments")
			return
		}
		logger.Info().Func(logHandle).Msg("call getOrderDocuments")
	}(time.Now())
	return m.next.GetOrderDocuments(ctx, orderID, userID)
}

func (m loggerOrdersAPI) GetOrderHistory(ctx context.Context, orderID uuid.UUID, userID uuid.UUID) (response models.GetOrderHistoryResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "getOrderHistory").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.getOrderHistory",
				"request": viewer.Sprintf("%+v", requestOrdersAPIGetOrderHistory{
					OrderID: orderID,
					UserID:  userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIGetOrderHistory{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getOrderHistory")
			return
		}
		logger.Info().Func(logHandle).Msg("call getOrderHistory")
	}(time.Now())
	return m.next.GetOrderHistory(ctx, orderID, userID)
}

func (m loggerOrdersAPI) UpdateOrderStatus(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, status string, paymentStatus string, comment string, changedBy string) (response models.UpdateOrderStatusResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "updateOrderStatus").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "ordersAPI.updateOrderStatus",
				"request": viewer.Sprintf("%+v", requestOrdersAPIUpdateOrderStatus{
					ChangedBy:     changedBy,
					Comment:       comment,
					OrderID:       orderID,
					PaymentStatus: paymentStatus,
					Status:        status,
					UserID:        userID,
				}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIUpdateOrderStatus{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateOrderStatus")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateOrderStatus")
	}(time.Now())
	return m.next.UpdateOrderStatus(ctx, userID, orderID, status, paymentStatus, comment, changedBy)
}

func (m loggerOrdersAPI) GetCities(ctx context.Context) (response []models.GetCities, err error) {
	logger := log.Ctx(ctx).With().Str("service", "OrdersAPI").Str("method", "getCities").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "ordersAPI.getCities",
				"request":  viewer.Sprintf("%+v", requestOrdersAPIGetCities{}),
				"response": viewer.Sprintf("%+v", responseOrdersAPIGetCities{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getCities")
			return
		}
		logger.Info().Func(logHandle).Msg("call getCities")
	}(time.Now())
	return m.next.GetCities(ctx)
}
