// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"strconv"
	"time"

	v2 "github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"github.com/mbatimel/AMC/orders/pkg/interfaces/externalAPI"
	"github.com/mbatimel/AMC/orders/pkg/models"
)

type metricsOrdersAPI struct {
	next externalAPI.OrdersAPI
}

func metricsMiddlewareOrdersAPI(next externalAPI.OrdersAPI) externalAPI.OrdersAPI {
	return &metricsOrdersAPI{next: next}
}

func (m metricsOrdersAPI) GetCart(ctx context.Context, userID uuid.UUID, clientID string) (models.GetCartResponse, error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("ordersAPI", "getCart", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("ordersAPI", "getCart", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("ordersAPI", "getCart", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.GetCart(ctx, userID, clientID)
}
