// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/users/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/AMC/users/pkg/interfaces/externalAPI"
	"github.com/mbatimel/AMC/users/pkg/models"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerUsersAPI struct {
	next externalAPI.UsersAPI
}

func loggerMiddlewareUsersAPI() MiddlewareUsersAPI {
	return func(next externalAPI.UsersAPI) externalAPI.UsersAPI {
		return &loggerUsersAPI{next: next}
	}
}

func (m loggerUsersAPI) CreateUser(ctx context.Context, email string, phone string, firstName string, lastName string, middleName string, role string, status string, clientID string, companyName string, inn string, isActive bool) (response models.CreateUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "createUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "usersAPI.createUser",
				"request": viewer.Sprintf("%+v", requestUsersAPICreateUser{
					ClientID:    clientID,
					CompanyName: companyName,
					Email:       email,
					FirstName:   firstName,
					Inn:         inn,
					IsActive:    isActive,
					LastName:    lastName,
					MiddleName:  middleName,
					Phone:       phone,
					Role:        role,
					Status:      status,
				}),
				"response": viewer.Sprintf("%+v", responseUsersAPICreateUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call createUser")
	}(time.Now())
	return m.next.CreateUser(ctx, email, phone, firstName, lastName, middleName, role, status, clientID, companyName, inn, isActive)
}

func (m loggerUsersAPI) GetUser(ctx context.Context, userID uuid.UUID) (response models.GetUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "getUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "usersAPI.getUser",
				"request":  viewer.Sprintf("%+v", requestUsersAPIGetUser{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseUsersAPIGetUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call getUser")
	}(time.Now())
	return m.next.GetUser(ctx, userID)
}

func (m loggerUsersAPI) ListUsers(ctx context.Context, q string, role string, status string, clientID string, isActive bool, limit int, offset int, sort string) (response models.ListUsersResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "listUsers").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "usersAPI.listUsers",
				"request": viewer.Sprintf("%+v", requestUsersAPIListUsers{
					ClientID: clientID,
					IsActive: isActive,
					Limit:    limit,
					Offset:   offset,
					Q:        q,
					Role:     role,
					Sort:     sort,
					Status:   status,
				}),
				"response": viewer.Sprintf("%+v", responseUsersAPIListUsers{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listUsers")
			return
		}
		logger.Info().Func(logHandle).Msg("call listUsers")
	}(time.Now())
	return m.next.ListUsers(ctx, q, role, status, clientID, isActive, limit, offset, sort)
}

func (m loggerUsersAPI) UpdateUser(ctx context.Context, userID uuid.UUID, email string, phone string, firstName string, lastName string, middleName string, role string, status string, clientID string, companyName string, inn string, isActive bool) (response models.UpdateUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "updateUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "usersAPI.updateUser",
				"request": viewer.Sprintf("%+v", requestUsersAPIUpdateUser{
					ClientID:    clientID,
					CompanyName: companyName,
					Email:       email,
					FirstName:   firstName,
					Inn:         inn,
					IsActive:    isActive,
					LastName:    lastName,
					MiddleName:  middleName,
					Phone:       phone,
					Role:        role,
					Status:      status,
					UserID:      userID,
				}),
				"response": viewer.Sprintf("%+v", responseUsersAPIUpdateUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateUser")
	}(time.Now())
	return m.next.UpdateUser(ctx, userID, email, phone, firstName, lastName, middleName, role, status, clientID, companyName, inn, isActive)
}

func (m loggerUsersAPI) DeleteUser(ctx context.Context, userID uuid.UUID) (response models.DeleteUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "deleteUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "usersAPI.deleteUser",
				"request":  viewer.Sprintf("%+v", requestUsersAPIDeleteUser{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseUsersAPIDeleteUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteUser")
	}(time.Now())
	return m.next.DeleteUser(ctx, userID)
}

func (m loggerUsersAPI) ActivateUser(ctx context.Context, userID uuid.UUID) (response models.ActivateUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "activateUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "usersAPI.activateUser",
				"request":  viewer.Sprintf("%+v", requestUsersAPIActivateUser{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseUsersAPIActivateUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call activateUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call activateUser")
	}(time.Now())
	return m.next.ActivateUser(ctx, userID)
}

func (m loggerUsersAPI) DeactivateUser(ctx context.Context, userID uuid.UUID) (response models.DeactivateUserResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "UsersAPI").Str("method", "deactivateUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "usersAPI.deactivateUser",
				"request":  viewer.Sprintf("%+v", requestUsersAPIDeactivateUser{UserID: userID}),
				"response": viewer.Sprintf("%+v", responseUsersAPIDeactivateUser{Response: response}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deactivateUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call deactivateUser")
	}(time.Now())
	return m.next.DeactivateUser(ctx, userID)
}
