// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"

	"github.com/google/uuid"
	"github.com/mbatimel/AMC/users/pkg/interfaces/externalAPI"
	"github.com/mbatimel/AMC/users/pkg/models"
)

type UsersAPICreateUser func(ctx context.Context, email string, phone string, firstName string, lastName string, middleName string, role string, status string, clientID string, companyName string, inn string, isActive bool) (response models.CreateUserResponse, err error)
type UsersAPIGetUser func(ctx context.Context, userID uuid.UUID) (response models.GetUserResponse, err error)
type UsersAPIListUsers func(ctx context.Context, q string, role string, status string, clientID string, isActive bool, limit int, offset int, sort string) (response models.ListUsersResponse, err error)
type UsersAPIUpdateUser func(ctx context.Context, userID uuid.UUID, email string, phone string, firstName string, lastName string, middleName string, role string, status string, clientID string, companyName string, inn string, isActive bool) (response models.UpdateUserResponse, err error)
type UsersAPIDeleteUser func(ctx context.Context, userID uuid.UUID) (response models.DeleteUserResponse, err error)
type UsersAPIActivateUser func(ctx context.Context, userID uuid.UUID) (response models.ActivateUserResponse, err error)
type UsersAPIDeactivateUser func(ctx context.Context, userID uuid.UUID) (response models.DeactivateUserResponse, err error)

type MiddlewareUsersAPI func(next externalAPI.UsersAPI) externalAPI.UsersAPI

type MiddlewareUsersAPICreateUser func(next UsersAPICreateUser) UsersAPICreateUser
type MiddlewareUsersAPIGetUser func(next UsersAPIGetUser) UsersAPIGetUser
type MiddlewareUsersAPIListUsers func(next UsersAPIListUsers) UsersAPIListUsers
type MiddlewareUsersAPIUpdateUser func(next UsersAPIUpdateUser) UsersAPIUpdateUser
type MiddlewareUsersAPIDeleteUser func(next UsersAPIDeleteUser) UsersAPIDeleteUser
type MiddlewareUsersAPIActivateUser func(next UsersAPIActivateUser) UsersAPIActivateUser
type MiddlewareUsersAPIDeactivateUser func(next UsersAPIDeactivateUser) UsersAPIDeactivateUser
