// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/AMC/users/pkg/interfaces/externalAPI"
)

type httpUsersAPI struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverUsersAPI
	base             externalAPI.UsersAPI
}

func NewUsersAPI(svcUsersAPI externalAPI.UsersAPI) (srv *httpUsersAPI) {

	srv = &httpUsersAPI{
		base: svcUsersAPI,
		svc:  newServerUsersAPI(svcUsersAPI),
	}
	return
}

func (http *httpUsersAPI) Service() *serverUsersAPI {
	return http.svc
}

func (http *httpUsersAPI) WithLog() *httpUsersAPI {
	http.svc.WithLog()
	return http
}

func (http *httpUsersAPI) WithMetrics() *httpUsersAPI {
	http.svc.WithMetrics()
	return http
}

func (http *httpUsersAPI) WithErrorHandler(handler ErrorHandler) *httpUsersAPI {
	http.errorHandler = handler
	return http
}

func (http *httpUsersAPI) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/users", http.serveCreateUser)
	route.Get("/api/v1/users", http.serveListUsers)
	route.Get("/api/v1/users/profile", http.serveGetProfile)
	route.Patch("/api/v1/users/profile", http.serveUpdateProfile)
	route.Get("/api/v1/users/profile/clients", http.serveListUserClients)
	route.Get("/api/v1/users/profile/clients/:clientID", http.serveGetClientDetails)
	route.Get("/api/v1/users/profile/clients/:clientID/conditions", http.serveGetClientConditions)
	route.Post("/api/v1/users/profile/clients/:clientID/activate", http.serveSwitchActiveClient)
	route.Get("/api/v1/users/favorites", http.serveListFavorites)
	route.Post("/api/v1/users/favorites", http.serveAddFavorite)
	route.Delete("/api/v1/users/favorites", http.serveDeleteFavorites)
	route.Get("/api/v1/users/:userID", http.serveGetUser)
	route.Patch("/api/v1/users/:userID", http.serveUpdateUser)
	route.Delete("/api/v1/users/:userID", http.serveDeleteUser)
	route.Post("/api/v1/users/:userID/activate", http.serveActivateUser)
	route.Post("/api/v1/users/:userID/deactivate", http.serveDeactivateUser)
}
