name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    name: Push Docker image to ghcr
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: access
            dockerfile: ./back/access/Dockerfile
            image: ghcr.io/mbatimel/amc-access
          - name: admin
            dockerfile: ./back/admin/Dockerfile
            image: ghcr.io/mbatimel/amc-admin
          - name: auth
            dockerfile: ./back/auth/Dockerfile
            image: ghcr.io/mbatimel/amc-auth
          - name: integrations
            dockerfile: ./back/integrations/Dockerfile
            image: ghcr.io/mbatimel/amc-onec-sync
          - name: migrations
            dockerfile: ./back/migrations/Dockerfile
            image: ghcr.io/mbatimel/amc-migrations
          - name: orders
            dockerfile: ./back/orders/Dockerfile
            image: ghcr.io/mbatimel/amc-orders
          - name: products
            dockerfile: ./back/products/Dockerfile
            image: ghcr.io/mbatimel/amc-products
          - name: users
            dockerfile: ./back/users/Dockerfile
            image: ghcr.io/mbatimel/amc-users
          - name: front
            dockerfile: ./front/Dockerfile
            image: ghcr.io/mbatimel/amc-front
          - name: admin-front
            dockerfile: ./admin-front/Dockerfile
            image: ghcr.io/mbatimel/amc-admin-front
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AMC_MBATIMEL }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.service.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
